import type { Copy } from "./ko";

export const en: Copy = {
  meta: {
    title: "MATCHU — Pick one color. We’ll match the rest.",
    description: "Turn a single HEX into a complete color system for web and app.",
  },
  localeName: "English",
  otherLocaleName: "한국어",
  brand: "MATCHU",
  nav: {
    generate: "Match my color",
    sample: "View a sample",
  },
  hero: {
    taglineA: "Pick one color.",
    taglineB: "We’ll match everything else.",
    taglineReady: "Ready to match?",
    doneTitle: "Everything matches.",
    doneBody: "Your UI color system is ready.",
    support: "Color is the result, not the decoration. The bench stays gray until you MATCH.",
    primaryCta: "Match my color",
    match: "MATCH",
    matched: "Matched",
    viewResult: "Open the full system",
    sampleCta: "View a sample",
    chips: "Web · App · Accessibility · Code export",
    hexLabel: "Main Color",
    pickHint: "Click me to pick a color!",
    generate: "Generate",
    appleLabel: "Apple color picker",
  },
  features: {
    title: "One color.\nMatched to every role.",
    roleTitle: "Matched by role",
    roleBody: "From background to type",
    screenTitle: "Matched across screens",
    screenBody: "Web and app, side by side",
    readTitle: "Matched for readability",
    readBody: "Looks good and reads clearly",
    codeTitle: "Matched to your stack",
    codeBody: "Copy and paste, ready to ship",
  },
  input: {
    title: "Main Color",
    subtitle: "Enter the main color your brand will be built around.",
    step1: "Step 1",
    step1Title: "Main Color",
    step2: "Step 2",
    step2Title: "Platform",
    step2Hint: "Pick WEB or APP to continue",
    moodTitle: "How should we match it?",
    targetTitle: "Where should we match it?",
    applyPalette: "Match this palette",
    palettesTitle: "Extracted palettes",
    advanced: "Advanced",
    neutral: "Neutral",
    secondary: "Secondary",
    accessibility: "Contrast target",
    cta: "Match my color",
    invalid: "Enter a valid HEX, RGB, HSL, or OKLCH value.",
    moods: {
      balanced: "Balanced",
      vivid: "Vivid",
      soft: "Soft",
      calm: "Calm",
      bright: "Bright",
      highContrast: "High contrast",
    },
    targets: {
      web: "WEB",
      app: "APP",
      both: "WEB + APP",
    },
    neutrals: {
      pure: "Pure gray",
      warm: "Warm gray",
      cool: "Cool gray",
      tinted: "Brand-tinted",
    },
    secondaries: {
      monochrome: "Monochrome",
      analogous: "Analogous",
      split: "Split",
      complementary: "Complementary",
    },
  },
  loading: {
    title: "Matching your colors",
    phrases: [
      "Analyzing your pick: {hex}.",
      "Building palettes around {hex}.",
      "{count} palette styles are ready.",
    ],
  },
  result: {
    title: "Everything matches.",
    body: "Your UI color system is ready.",
    colors: "{count} colors",
    platforms: "Web + app",
    contrast: "{count} contrast issues",
    copy: "Copy code",
    export: "Export",
    save: "Save",
    share: "Share",
    saved: "Saved to this browser",
    copied: "Copied the color token.",
    shared: "Share this match.",
    shareFailed: "Could not create a share link.",
    copyFailed: "Clipboard access was denied.",
    fixContrast: "Fix contrast",
    web: "Web",
    app: "App",
    matching: "Matching your colors",
    palette: "Palette",
    palettePicker: "Color palettes",
    tokens: "Color tokens",
    remake: "Start over",
    remakeHint: "Pick a new main color",
    remakeAppleTip: "Click me if you want to make a new color palette.",
    moreMenu: "More",
  },
  preview: {
    overview: "Find a class",
    components: "UI Kit",
    states: "States",
    colors: "Colors",
    screens: {
      dashboard: "Dashboard",
      marketing: "Marketing",
      form: "Form",
      data: "Data",
      feedback: "Feedback",
      home: "Home",
      list: "List",
      detail: "Detail",
      settings: "Settings",
    },
    kindPicker: "Preview type",
    kinds: {
      work: "Work",
      shop: "Shop",
      finance: "Finance",
      travel: "Travel",
      community: "Community",
      education: "Learn",
      health: "Health",
      media: "Media",
      food: "Food",
    },
    usage: "Token use",
    toolbarWeb: "Web · 1440 · Fit",
    toolbarApp: "App · 390×844",
    highlightOff: "Clear highlight",
    contrastOk: "No contrast warnings",
    contrastWarn: "{count} contrast warnings",
    mobile: {
      preview: "Preview",
      tokens: "Tokens",
      export: "Export",
    },
    kit: {
      actions: "Actions",
      inputs: "Inputs",
      navigation: "Navigation",
      data: "Data",
      feedback: "Feedback",
      states: "States",
      primary: "Primary",
      other: "Other",
      fieldStates: "Field states",
      choices: "Choices",
      tabsPager: "Tabs / breadcrumb / pages",
      cardListBadge: "Card / list / badge",
      alerts: "Alerts",
      hoverFocusDisabled: "Hover / focus / disabled",
      pressedFocusDisabled: "Pressed / focused / disabled",
      default: "Default",
      hover: "Hover",
      pressed: "Pressed",
      active: "Active",
      disabled: "Disabled",
      loading: "Loading",
      secondary: "Secondary",
      tertiary: "Tertiary",
      ghost: "Ghost",
      destructive: "Delete",
      accent: "Accent",
      link: "Link",
      empty: "Empty",
      filled: "Filled",
      focus: "Focus",
      error: "Error",
      textarea: "Multiline",
      checkbox: "Checkbox",
      radioWeekly: "Weekly",
      radioMonthly: "Monthly",
      breadcrumb: "Home / Library / Northwind",
      all: "All",
      inProgress: "Active",
      done: "Done",
      prev: "Prev",
      next: "Next",
      pageOf: "{page} / {total}",
      chipCalm: "Calm",
      chipVivid: "Vivid",
      emptyState: "Nothing here yet",
      success: "Success",
      successBody: "Saved.",
      warning: "Warning",
      warningBody: "This needs a look.",
      errorTitle: "Error",
      errorBody: "Try again.",
      info: "Info",
      infoBody: "Status colors stay separate from the palette.",
      lastAction: "Last action: {action}",
      idle: "Press a button to see its state",
      saved: "Saved",
      deleted: "Deleted",
      linked: "Opened the link",
      switchOn: "On",
      switchOff: "Off",
      tabAll: "{count} total",
      tabActive: "{count} active",
      tabDone: "{count} done",
      notify: "Get alerts",
      openModal: "Open modal",
      modalTitle: "Confirm this action?",
      modalBody: "Use a filled Primary button for the one main action.",
      cancel: "Close",
      confirm: "Confirm",
      help: "Help",
      helpTip: "Keep Accent to 5–10% of the surface.",
      formControls: "Form controls",
      selectionControls: "Selection controls",
      disableFields: "Disable fields",
      loginTitle: "Log in",
      loginDescription: "Use your email account to continue.",
      loginEmail: "Email ID",
      loginIdPlaceholder: "Username",
      loginIdError: "Use letters, numbers, dots, or underscores only.",
      emailDomain: "Email domain",
      domainCustom: "Enter manually",
      customDomainPlaceholder: "Enter email domain",
      emailDomainError: "Enter a valid email domain.",
      loginEmailHint: "Enter your ID and choose an email domain.",
      loginPassword: "Password",
      passwordPlaceholder: "Enter password",
      passwordRule: "Use 8–16 characters with letters, numbers, and symbols.",
      passwordError: "The password does not meet the requirements.",
      login: "Log in",
      loggingIn: "Logging in",
      loggedIn: "Done",
      loginReset: "Start over",
      loginSuccess: "You are logged in.",
      plan: "Plan",
      selectPlaceholder: "Choose a plan",
      selectError: "Choose one plan.",
      selectHint: "Open it to test options and selection.",
      planStarter: "Starter",
      planTeam: "Team",
      planBusiness: "Business",
      notePlaceholder: "Write at least 10 characters.",
      noteError: "Enter at least 10 characters.",
      noteHint: "Test typing, resizing, and focus.",
      acceptTerms: "Accept the terms",
      checked: "Checked",
      unchecked: "Unchecked",
      radio: "Radio",
      switch: "Switch",
      accessibility: "ACCESSIBILITY",
      accessibilityTitle: "Accessibility settings",
      accessibilityBody: "Adjust the display and motion for comfortable viewing.",
      nightMode: "Night mode",
      fontSize: "Text size",
      fontSmall: "Small",
      fontMedium: "Medium",
      fontLarge: "Large",
      fontSample: "MATCHU makes interfaces comfortable and delightful to use.",
      motionSettings: "Motion settings",
      appleMotion: "Apple bounce",
      appleBlink: "Eye blinking",
      applePreview: "Apple motion preview",
      chatTitle: "Support chat",
      chatStatus: "Available",
      chatGreeting: "Hi. Feel free to tell me what's on your mind.",
      chatPlaceholder: "Write a message",
      chatSend: "Send message",
      chatTyping: "Writing a reply…",
      chatReplies: [
        "I see.",
        "Thank you for sharing that.",
        "Yes, I understand.",
        "Could you tell me a little more about that?",
        "That's how you're seeing it.",
        "Please, go on.",
      ],
      searchPlaceholder: "Search",
      searchOptions: ["Design system", "Color palette", "UI component", "Prototype"],
      noSearchResults: "No results found.",
      multiSelect: "Interests",
      multiSelectPlaceholder: "Choose interests",
      multiSelectCount: "{n} selected",
      multiSelectDesign: "Design",
      multiSelectDevelopment: "Development",
      multiSelectMarketing: "Marketing",
      multiSelectResearch: "Research",
      quantity: "Quantity",
      decreaseQuantity: "Decrease quantity",
      increaseQuantity: "Increase quantity",
      rating: "Rating",
      slider: "Slider",
      feedbackActions: "Feedback · overlay actions",
      actionConfirmModal: "Modal",
      actionDrawer: "Drawer",
      actionPopover: "Popover",
      actionTooltip: "Tooltip",
      actionLoading: "Loading Overlay",
      successAlertTitle: "Saved",
      successAlertBody: "Your changes were saved safely.",
      infoAlertTitle: "New information",
      infoAlertBody: "There is something new for you to review.",
      warningAlertTitle: "Check this first",
      warningAlertBody: "Review the entered information before continuing.",
      errorAlertTitle: "Something went wrong",
      errorAlertBody: "Please try again in a moment.",
      confirmModalTitle: "Apply these changes?",
      confirmModalBody: "The selected settings will be applied to this screen.",
      drawerTitle: "Details",
      drawerBody: "Review additional options and details in this panel.",
      popoverTitle: "Quick help",
      popoverBody: "A popover shows brief information without losing context.",
      tooltipBody: "A short description shown over the button.",
      loadingBody: "Working…",
      close: "Close",
      dataCharts: "Data charts",
      barChart: "Weekly activity",
      chartCaption: "Select a bar to inspect its value.",
      chartLabels: ["Search", "Sign-up", "Active", "Payment", "Return"],
      selectableTable: "Selectable data table",
      tableTitle: "Recent projects",
      tableCaption: "Select a row or sort a column.",
      tableSelected: "selected",
      tableSelect: "Select row",
      tableName: "Project",
      tableOwner: "Owner",
      tableStatus: "Status",
      tableAmount: "Score",
      tableItems: ["Brand refresh", "Mobile app", "Checkout", "Research", "Archived project"],
      tableOwners: ["Minjun", "Seoyeon", "Jiwoo", "Hajun", "Yerin"],
      tableStatusLabels: ["Done", "In progress", "Review", "Delayed", "Disabled"],
      extendedKit: {
        title: "States · navigation · data input",
        badges: "Badge · Chip · Tag",
        complete: "Complete",
        inProgress: "In progress",
        review: "Needs review",
        delayed: "Delayed",
        design: "Design",
        development: "Development",
        marketing: "Marketing",
        tag: "Color tokens",
        removeTag: "Remove tag",
        restoreTag: "Restore tag",
        tabsSegments: "Tabs · Segmented Control",
        overview: "Overview",
        activity: "Activity",
        settings: "Settings",
        overviewBody: "Review the service's key information.",
        activityBody: "Review recent changes and user activity.",
        settingsBody: "Configure display and notifications.",
        weekly: "Weekly",
        monthly: "Monthly",
        yearly: "Yearly",
        loadingStates: "Progress · Skeleton · Spinner",
        uploadProgress: "Upload progress",
        advance: "Advance progress",
        loading: "Loading data",
        skeleton: "Content loading preview",
        emptyStates: "Empty State",
        empty: "Empty",
        noResults: "No results",
        error: "Error",
        emptyTitle: "Nothing here yet",
        emptyBody: "New items will appear here.",
        noResultsTitle: "No results found",
        noResultsBody: "Try changing the query or filters.",
        errorTitle: "Could not load data",
        errorBody: "Please try again in a moment.",
        retry: "Retry",
        addItem: "Add item",
        accordion: "Accordion",
        accordionTokens: "Color tokens",
        accordionTokensBody: "Use Primary, Surface, and Text tokens by role.",
        accordionComponents: "Components",
        accordionComponentsBody: "Components share the same state and interaction rules.",
        accordionAccessibility: "Accessibility",
        accordionAccessibilityBody: "Maintain keyboard focus and sufficient contrast.",
        navigation: "Pagination · Breadcrumb",
        breadcrumb: "Current location",
        home: "Home",
        library: "Library",
        current: "UI Kit",
        page: "Viewing page {n}",
        pagination: "Pagination",
        previous: "Previous page",
        next: "Next page",
        dateTime: "Date · Time Picker",
        date: "Date",
        time: "Time",
        disabledDate: "Disabled date",
        fileUpload: "File Upload",
        dropFile: "Drop a file or choose one",
        uploadHint: "Image or PDF · up to 2MB",
        uploadComplete: "Ready to upload",
        uploadError: "Unsupported file",
        avatarList: "Avatar · List Item",
        memberOne: "Minkyung",
        memberTwo: "Jisu",
        memberThree: "Hayoon",
        designer: "Product designer",
        developer: "Frontend developer",
        marketer: "Marketer",
        menus: "Dropdown · Context Menu",
        actions: "Actions",
        edit: "Edit",
        duplicate: "Duplicate",
        archive: "Archive · disabled",
        contextTarget: "Project document.pdf",
        contextHint: "Right-click the area.",
        open: "Open",
        rename: "Rename",
        delete: "Delete",
        close: "Close",
      },
      products: {
        newBadge: "NEW",
        saleBadge: "SALE",
        soldOutBadge: "SOLD OUT",
        categoryKids: "Kids",
        categoryBackpack: "Men's backpack",
        categoryScarves: "Scarves",
        categoryShoes: "Shoes",
        jacketName: "Beige Check Black Collar Quilted Jacket",
        backpackName: "Knight Stamp Drawcord Backpack",
        scarfName: "Check Cashmere Scarf",
        sneakerName: "Leather and Check Terrace Sneakers",
        addToCart: "Add to cart",
        buyNow: "Buy now",
        soldOut: "Sold out",
        added: "Added",
      },
    },
    buttons: {
      color: "Buttons color",
      soft: "Soft buttons",
      outline: "Outline buttons",
      neutral: "Neutral",
      primary: "Primary",
      secondary: "Secondary",
      accent: "Accent",
      info: "Info",
      success: "Success",
      warning: "Warning",
      error: "Error",
    },
    gallery: {
      shoes: "Shoes",
      bags: "Bags",
      hoodies: "Hoodies",
      accessories: "Accessories",
      sale: "Sale",
      find: "Find",
      productTitle: "Daily sneakers",
      reviews: "{count} reviews",
      meeting: "Team sync",
      meetingBody: "Weekly review with design and engineering",
      hour: "1h",
      priceRange: "Price range",
      salesNote: "Sales are up 15% from last week.",
      charts: "Charts",
      details: "Details",
      pageScore: "Page score",
      allGood: "All good",
      recentOrders: "Recent orders",
      send: "Send",
      failed: "Failed",
      progressing: "In progress",
      completed: "Done",
      revenue: "September revenue",
      moreThanLast: "{n}% more than last month",
      newPost: "Write a new post",
      addFiles: "Add files",
      remaining: "{n} characters left",
      draft: "Draft",
      publish: "Publish",
      chatName: "Minjun",
      chatA: "The palette is locked in.",
      chatB: "Primary stays on buttons only.",
      delivered: "Delivered",
      playerTitle: "Afternoon focus mix",
      playerSub: "2 hours of focus",
      messages: "{n} new messages",
      verified: "Verification finished",
      verifyEmail: "Verify your email",
      denied: "Access denied",
      support: "Support",
      signupTitle: "Create an account",
      signupBody: "It’s free and takes a minute.",
      email: "Email",
      password: "Password",
      passwordHint: "Use at least 8 characters.",
      acceptTerms: "Accept the terms",
      subscribe: "Get updates",
      register: "Register",
      orLogin: "or log in",
      planTitle: "Starter plan",
      perMonth: "{price}/month",
      featureA: "20 tokens a day",
      featureB: "10 projects",
      featureC: "API access",
      buy: "Buy now",
      admin: "Admin",
      products: "Products",
      users: "Users",
      settings: "Settings",
      heroKicker: "Northwind",
      heroTitle: "What should we learn this weekend?",
      heroBody: "Once the color is set, the screens follow.",
      crumbHome: "Home",
      crumbLib: "Library",
      crumbNow: "Northwind",
      faqShip: "How long does shipping take?",
      faqShipBody: "Next day in Seoul, 2–3 days elsewhere.",
      faqReturn: "How do returns work?",
      faqReturnBody: "Request one within 7 days of delivery.",
      collapseMore: "Details",
      collapseBody: "Use Primary for one main action on the screen.",
      countLeft: "Until close",
      diffBefore: "Before",
      diffAfter: "After",
      drawerOpen: "Menu",
      drawerInbox: "Inbox",
      drawerTeam: "Team",
      dropSort: "Sort",
      dropNew: "Newest",
      dropOld: "Oldest",
      fabNote: "Note",
      fabUpload: "Upload",
      legendProfile: "Profile",
      filePick: "Choose file",
      city: "City",
      seoul: "Seoul",
      busan: "Busan",
      otp: "Code",
      footerDocs: "Docs",
      footerBlog: "Blog",
      footerCopy: "© MATCHU",
      toastOn: "Show toast",
      toastBody: "Saved.",
      rateThis: "Rate this product",
      stepCart: "Cart",
      stepPay: "Pay",
      stepDone: "Done",
      swapOn: "On",
      swapOff: "Off",
      rowA: "Sneakers",
      rowB: "Hoodie",
      qty: "Qty",
      rotateA: "Pick a palette",
      rotateB: "Paint the screens",
      rotateC: "Take the code",
      eventPlan: "Plan",
      eventBuild: "Build",
      eventShip: "Ship",
      online: "Online",
      away: "Away",
      offline: "Offline",
      shortcut: "Save",
      searchJoin: "Search",
      codeSample: "const theme = tokens",
      phoneApp: "MATCHU",
      windowTitle: "Preview",
      megaShop: "Shop",
      megaNew: "New",
      megaSale: "Sale",
      listUnread: "Unread",
      listStar: "Starred",
      maskNote: "Mask",
      skelWait: "Loading",
      upload: "Upload",
      linkDocs: "View docs",
      homeDock: "Home",
    },
  },
  tokens: {
    title: "Color tokens",
    viewAll: "All tokens",
    viewCore: "Core tokens",
    resetAll: "Cancel all",
    undo: "Undo",
    close: "Close color tokens",
    usesLabel: "Used for",
    groups: {
      core: "Core Colors",
      background: "Background & Surface",
      text: "Text",
      border: "Border",
      status: "Status",
      interaction: "Interaction",
      primitive: "Primitive scales",
      all: "All semantic",
    },
    labels: {
      primary: "Primary",
      secondary: "Secondary",
      accent: "Accent",
      onPrimary: "On Primary",
      onSecondary: "On Secondary",
      onAccent: "On Accent",
      primarySubtle: "Primary Subtle",
      background: "Background",
      backgroundSubtle: "Subtle Background",
      surface: "Surface",
      surfaceRaised: "Raised Surface",
      surfaceOverlay: "Overlay Surface",
      textPrimary: "Primary Text",
      textSecondary: "Secondary Text",
      textTertiary: "Tertiary Text",
      textDisabled: "Disabled Text",
      textInverse: "Inverse Text",
      textLink: "Link Text",
      borderSubtle: "Subtle Border",
      borderDefault: "Default Border",
      borderStrong: "Strong Border",
      borderFocus: "Focus Border",
      success: "Success",
      successSurface: "Success Surface",
      warning: "Warning",
      warningSurface: "Warning Surface",
      danger: "Danger",
      dangerSurface: "Danger Surface",
      info: "Info",
      infoSurface: "Info Surface",
      onSuccess: "On Success",
      onWarning: "On Warning",
      onDanger: "On Danger",
      onInfo: "On Info",
      primaryHover: "Primary Hover",
      primaryPressed: "Primary Pressed",
      primarySelected: "Primary Selected",
      secondaryHover: "Secondary Hover",
      secondaryPressed: "Secondary Pressed",
      neutralHover: "Neutral Hover",
      neutralPressed: "Neutral Pressed",
      focusRing: "Focus Ring",
      disabledSurface: "Disabled Surface",
      disabledBorder: "Disabled Border",
    },
    guides: {
      primary: {
        role: "The brand identity color. Use it for the most important actions and selections.",
        uses: "Primary CTA buttons, active tabs, key icons, checked states",
      },
      secondary: {
        role: "Supports Primary and separates a second function or information area.",
        uses: "Secondary buttons, supporting categories, secondary charts",
      },
      accent: {
        role: "Pulls attention briefly and strongly.",
        uses: "New features, emphasis badges, promotions, highlights",
      },
      surface: {
        role: "The default surface content and components sit on.",
        uses: "Cards, inputs, panels, modal interiors",
      },
      onPrimary: {
        role: "Content color on Primary. Chosen by contrast against that background, not always white.",
        uses: "Primary button text and icons",
      },
      onSecondary: {
        role: "Content color on Secondary. Chosen by contrast against that background.",
        uses: "Secondary button text and icons",
      },
      onAccent: {
        role: "Content color on Accent. Chosen by contrast against that background.",
        uses: "Accent badge and button text and icons",
      },
      primarySubtle: {
        role: "A tinted Primary used for quieter selection or emphasis.",
        uses: "Selected menu backgrounds, tags, info boxes, Primary icon backgrounds",
      },
      background: {
        role: "The outermost page or app background.",
        uses: "Body, full-screen app canvas",
      },
      backgroundSubtle: {
        role: "A softer background that divides regions inside the screen.",
        uses: "Sidebars, section backgrounds, table headers",
      },
      surfaceRaised: {
        role: "A surface that sits above the default background.",
        uses: "Cards, dropdowns, floating panels",
      },
      surfaceOverlay: {
        role: "A surface layered over the current screen.",
        uses: "Modals, dialogs, popovers, bottom sheets",
      },
      textPrimary: {
        role: "The highest-priority default text.",
        uses: "Titles, body copy, key metrics",
      },
      textSecondary: {
        role: "Supporting text with lower priority than body copy.",
        uses: "Descriptions, extra detail, metadata",
      },
      textTertiary: {
        role: "Readable information that should not compete for attention.",
        uses: "Dates, captions, help text, secondary labels",
      },
      textDisabled: {
        role: "Text for controls that cannot be used. Not just low-priority copy.",
        uses: "Disabled buttons, disabled menus, locked inputs",
      },
      textInverse: {
        role: "Reversed text for dark or strongly colored backgrounds.",
        uses: "Dark surfaces, image overlays, color banners",
      },
      textLink: {
        role: "Marks text that can be clicked or navigated.",
        uses: "Inline links, learn more, URLs",
      },
      borderSubtle: {
        role: "A light edge that separates regions without a hard divide.",
        uses: "Card dividers, list dividers, table rows",
      },
      borderDefault: {
        role: "The default outline of a component.",
        uses: "Inputs, buttons, cards",
      },
      borderStrong: {
        role: "A stronger edge for clearer separation or emphasis.",
        uses: "Selected regions, important cards, highlighted sections",
      },
      borderFocus: {
        role: "Shows the keyboard or input focus. Prefer a 2px-or-thicker focus ring.",
        uses: "Focused inputs, buttons, selects",
      },
      success: {
        role: "Success, healthy state, or completion.",
        uses: "Success icons, complete badges, success messages",
      },
      successSurface: {
        role: "A tinted background for success information.",
        uses: "Success alerts, completed card backgrounds",
      },
      warning: {
        role: "Needs attention, but is not an immediate failure.",
        uses: "Warning icons, caution badges, review-needed states",
      },
      warningSurface: {
        role: "A tinted background for warning information.",
        uses: "Warning alerts, caution boxes",
      },
      danger: {
        role: "Error, failure, deletion, or a dangerous action.",
        uses: "Delete buttons, error messages, failure badges",
      },
      dangerSurface: {
        role: "A tinted background for errors and delete warnings.",
        uses: "Error alerts, delete confirmation boxes",
      },
      info: {
        role: "Neutral guidance or reference information.",
        uses: "Help, notices, info badges",
      },
      infoSurface: {
        role: "A tinted background for notices and info boxes.",
        uses: "Help boxes, info alerts",
      },
      onSuccess: {
        role: "Text and icons on Success fills, chosen by contrast.",
        uses: "Success badges, complete buttons",
      },
      onWarning: {
        role: "Text and icons on Warning fills, chosen by contrast.",
        uses: "Warning badges, caution buttons",
      },
      onDanger: {
        role: "Text and icons on Danger fills, chosen by contrast.",
        uses: "Delete buttons, error badges",
      },
      onInfo: {
        role: "Text and icons on Info fills, chosen by contrast.",
        uses: "Info badges, notice buttons",
      },
      primaryHover: {
        role: "A Primary control with a pointer over it.",
        uses: "Primary CTA buttons, active icon buttons, Primary links",
      },
      primaryPressed: {
        role: "A Primary control being clicked or touched.",
        uses: "CTA buttons mid-click, Primary buttons mid-touch",
      },
      primarySelected: {
        role: "A Primary item that stays selected.",
        uses: "Selected tabs, active menus, selected filters and options",
      },
      secondaryHover: {
        role: "A Secondary control with a pointer over it.",
        uses: "Secondary buttons, supporting actions, Secondary icon buttons",
      },
      secondaryPressed: {
        role: "A Secondary control being clicked or touched.",
        uses: "Secondary buttons mid-click or mid-touch",
      },
      neutralHover: {
        role: "Hover for ordinary elements that do not use brand color.",
        uses: "List items, table rows, dropdown options, neutral buttons",
      },
      neutralPressed: {
        role: "A neutral element being clicked or touched.",
        uses: "List items, menus, cards, neutral icon buttons",
      },
      focusRing: {
        role: "The outline for keyboard focus or the current input target.",
        uses: "Buttons, inputs, selects, checkboxes, links",
      },
      disabledSurface: {
        role: "The inactive background of a control that cannot be used.",
        uses: "Disabled buttons, inputs, selects, toggles",
      },
      disabledBorder: {
        role: "The inactive edge of a control that cannot be used.",
        uses: "Disabled inputs, buttons, checkboxes, radios",
      },
    },
  },
  export: {
    title: "Export",
    css: "CSS",
    tailwind: "Tailwind",
    reactNative: "React Native",
    json: "JSON",
    figma: "Figma",
    download: "Download",
    copy: "Copy",
  },
  share: {
    title: "Share this match.",
    invalid: "This share link is damaged or incomplete.",
    back: "Back home",
  },
  notFound: {
    title: "This page isn’t a match.",
    body: "Check the address, or start again from a main color.",
    cta: "Back home",
  },
};
