import type { Copy } from "./ko";

export const en: Copy = {
  meta: {
    title: "MATCHU — Pick one color. We’ll match the rest.",
    description: "Turn a single HEX into a complete color system for web and app.",
  },
  localeName: "English",
  otherLocaleName: "한국어",
  brand: "MATCHU",
  nav: {
    generate: "Match my color",
    sample: "View a sample",
  },
  hero: {
    taglineA: "Pick one color.",
    taglineB: "We’ll match everything else.",
    taglineReady: "Ready to match?",
    doneTitle: "Everything matches.",
    doneBody: "Your UI color system is ready.",
    support: "Color is the result, not the decoration. The bench stays gray until you MATCH.",
    primaryCta: "Match my color",
    match: "MATCH",
    matched: "Matched",
    viewResult: "Open the full system",
    sampleCta: "View a sample",
    chips: "Web · App · Accessibility · Code export",
    hexLabel: "Main Color",
  },
  features: {
    title: "One color.\nMatched to every role.",
    roleTitle: "Matched by role",
    roleBody: "From background to type",
    screenTitle: "Matched across screens",
    screenBody: "Web and app, side by side",
    readTitle: "Matched for readability",
    readBody: "Looks good and reads clearly",
    codeTitle: "Matched to your stack",
    codeBody: "Copy and paste, ready to ship",
  },
  input: {
    title: "Main Color",
    subtitle: "Enter the main color your brand will be built around.",
    step1: "Step 1",
    step1Title: "Main Color",
    step2: "Step 2",
    step2Title: "Platform",
    step2Hint: "Pick WEB or APP to continue",
    moodTitle: "How should we match it?",
    targetTitle: "Where should we match it?",
    applyPalette: "Match this palette",
    palettesTitle: "Extracted palettes",
    advanced: "Advanced",
    neutral: "Neutral",
    secondary: "Secondary",
    accessibility: "Contrast target",
    cta: "Match my color",
    invalid: "Enter a valid HEX, RGB, HSL, or OKLCH value.",
    moods: {
      balanced: "Balanced",
      vivid: "Vivid",
      soft: "Soft",
      calm: "Calm",
      bright: "Bright",
      highContrast: "High contrast",
    },
    targets: {
      web: "WEB",
      app: "APP",
      both: "WEB + APP",
    },
    neutrals: {
      pure: "Pure gray",
      warm: "Warm gray",
      cool: "Cool gray",
      tinted: "Brand-tinted",
    },
    secondaries: {
      monochrome: "Monochrome",
      analogous: "Analogous",
      split: "Split",
      complementary: "Complementary",
    },
  },
  loading: {
    title: "Matching your colors",
    phrases: [
      "Reading your color",
      "Matching the rest",
      "Painting the screen",
    ],
  },
  result: {
    title: "Everything matches.",
    body: "Your UI color system is ready.",
    colors: "{count} colors",
    modes: "Light + dark",
    platforms: "Web + app",
    contrast: "{count} contrast issues",
    copy: "Copy code",
    export: "Export",
    save: "Save",
    share: "Share",
    saved: "Saved to this browser",
    copied: "Copied the color token.",
    shared: "Share this match.",
    shareFailed: "Could not create a share link.",
    copyFailed: "Clipboard access was denied.",
    fixContrast: "Fix contrast",
    light: "Light",
    dark: "Dark",
    web: "Web",
    app: "App",
    matching: "Matching your colors",
    palette: "Palette",
    palettePicker: "Color palettes",
    tokens: "Color tokens",
  },
  preview: {
    overview: "Find a class",
    components: "Components",
    states: "States",
    colors: "Colors",
    screens: {
      dashboard: "Dashboard",
      marketing: "Marketing",
      form: "Form",
      data: "Data",
      feedback: "Feedback",
      home: "Home",
      list: "List",
      detail: "Detail",
      settings: "Settings",
    },
    kindPicker: "Preview type",
    kinds: {
      work: "Work",
      shop: "Shop",
      finance: "Finance",
      travel: "Travel",
      community: "Community",
      education: "Learn",
      health: "Health",
      media: "Media",
      food: "Food",
    },
    usage: "Token use",
    toolbarWeb: "Web · 1440 · Fit",
    toolbarApp: "App · 390×844",
    highlightOff: "Clear highlight",
    contrastOk: "No contrast warnings",
    contrastWarn: "{count} contrast warnings",
    mobile: {
      preview: "Preview",
      tokens: "Tokens",
      export: "Export",
    },
  },
  tokens: {
    title: "Color tokens",
    viewAll: "View all tokens",
    viewCore: "Core tokens",
    groups: {
      core: "Core Colors",
      background: "Background & Surface",
      text: "Text",
      border: "Border",
      status: "Status",
      interaction: "Interaction",
      primitive: "Primitive scales",
      all: "All semantic",
    },
    labels: {
      primary: "Primary",
      secondary: "Secondary",
      accent: "Accent",
      onPrimary: "On Primary",
      onSecondary: "On Secondary",
      onAccent: "On Accent",
      primarySubtle: "Primary Subtle",
      background: "Background",
      backgroundSubtle: "Subtle Background",
      surface: "Surface",
      surfaceRaised: "Raised Surface",
      surfaceOverlay: "Overlay Surface",
      textPrimary: "Primary Text",
      textSecondary: "Secondary Text",
      textTertiary: "Tertiary Text",
      textDisabled: "Disabled Text",
      textInverse: "Inverse Text",
      textLink: "Link Text",
      borderSubtle: "Subtle Border",
      borderDefault: "Default Border",
      borderStrong: "Strong Border",
      borderFocus: "Focus Border",
      success: "Success",
      successSurface: "Success Surface",
      warning: "Warning",
      warningSurface: "Warning Surface",
      danger: "Danger",
      info: "Info",
      hover: "Hover",
      pressed: "Pressed",
      selected: "Selected",
      focus: "Focus",
      disabled: "Disabled",
    },
  },
  export: {
    title: "Export",
    css: "CSS",
    tailwind: "Tailwind",
    reactNative: "React Native",
    json: "JSON",
    download: "Download",
    copy: "Copy",
  },
  share: {
    title: "Share this match.",
    invalid: "This share link is damaged or incomplete.",
    back: "Back home",
  },
  notFound: {
    title: "This page isn’t a match.",
    body: "Check the address, or start again from a main color.",
    cta: "Back home",
  },
};
