import type { Copy } from "./ko";

export const en: Copy = {
  meta: {
    title: "MATCHU — Pick one color. We’ll match the rest.",
    description: "Turn a single HEX into a complete color system for web and app.",
  },
  localeName: "English",
  otherLocaleName: "한국어",
  brand: "MATCHU",
  nav: {
    generate: "Match my color",
    sample: "View a sample",
  },
  hero: {
    taglineA: "Pick one color.",
    taglineB: "We’ll match everything else.",
    taglineReady: "Ready to match?",
    doneTitle: "Everything matches.",
    doneBody: "Your UI color system is ready.",
    support: "Color is the result, not the decoration. The bench stays gray until you MATCH.",
    primaryCta: "Match my color",
    match: "MATCH",
    matched: "Matched",
    viewResult: "Open the full system",
    sampleCta: "View a sample",
    chips: "Web · App · Accessibility · Code export",
    hexLabel: "Main Color",
    pickHint: "Click me to pick a color!",
    generate: "Generate",
    appleLabel: "Apple color picker",
  },
  features: {
    title: "One color.\nMatched to every role.",
    roleTitle: "Matched by role",
    roleBody: "From background to type",
    screenTitle: "Matched across screens",
    screenBody: "Web and app, side by side",
    readTitle: "Matched for readability",
    readBody: "Looks good and reads clearly",
    codeTitle: "Matched to your stack",
    codeBody: "Copy and paste, ready to ship",
  },
  input: {
    title: "Main Color",
    subtitle: "Enter the main color your brand will be built around.",
    step1: "Step 1",
    step1Title: "Main Color",
    step2: "Step 2",
    step2Title: "Platform",
    step2Hint: "Pick WEB or APP to continue",
    moodTitle: "How should we match it?",
    targetTitle: "Where should we match it?",
    applyPalette: "Match this palette",
    palettesTitle: "Extracted palettes",
    advanced: "Advanced",
    neutral: "Neutral",
    secondary: "Secondary",
    accessibility: "Contrast target",
    cta: "Match my color",
    invalid: "Enter a valid HEX, RGB, HSL, or OKLCH value.",
    moods: {
      balanced: "Balanced",
      vivid: "Vivid",
      soft: "Soft",
      calm: "Calm",
      bright: "Bright",
      highContrast: "High contrast",
    },
    targets: {
      web: "WEB",
      app: "APP",
      both: "WEB + APP",
    },
    neutrals: {
      pure: "Pure gray",
      warm: "Warm gray",
      cool: "Cool gray",
      tinted: "Brand-tinted",
    },
    secondaries: {
      monochrome: "Monochrome",
      analogous: "Analogous",
      split: "Split",
      complementary: "Complementary",
    },
  },
  loading: {
    title: "Matching your colors",
    phrases: [
      "Analyzing your pick: {hex}.",
      "Building palettes around {hex}.",
      "{count} palette styles are ready.",
    ],
  },
  result: {
    title: "Everything matches.",
    body: "Your UI color system is ready.",
    colors: "{count} colors",
    modes: "Light + dark",
    platforms: "Web + app",
    contrast: "{count} contrast issues",
    copy: "Copy code",
    export: "Export",
    save: "Save",
    share: "Share",
    saved: "Saved to this browser",
    copied: "Copied the color token.",
    shared: "Share this match.",
    shareFailed: "Could not create a share link.",
    copyFailed: "Clipboard access was denied.",
    fixContrast: "Fix contrast",
    light: "Light",
    dark: "Dark",
    web: "Web",
    app: "App",
    matching: "Matching your colors",
    palette: "Palette",
    palettePicker: "Color palettes",
    tokens: "Color tokens",
    remake: "Start over",
    remakeHint: "Pick a new main color",
    moreMenu: "More",
  },
  preview: {
    overview: "Find a class",
    components: "Components",
    states: "States",
    colors: "Colors",
    screens: {
      dashboard: "Dashboard",
      marketing: "Marketing",
      form: "Form",
      data: "Data",
      feedback: "Feedback",
      home: "Home",
      list: "List",
      detail: "Detail",
      settings: "Settings",
    },
    kindPicker: "Preview type",
    kinds: {
      work: "Work",
      shop: "Shop",
      finance: "Finance",
      travel: "Travel",
      community: "Community",
      education: "Learn",
      health: "Health",
      media: "Media",
      food: "Food",
    },
    usage: "Token use",
    toolbarWeb: "Web · 1440 · Fit",
    toolbarApp: "App · 390×844",
    highlightOff: "Clear highlight",
    contrastOk: "No contrast warnings",
    contrastWarn: "{count} contrast warnings",
    mobile: {
      preview: "Preview",
      tokens: "Tokens",
      export: "Export",
    },
  },
  tokens: {
    title: "Color tokens",
    viewAll: "View all tokens",
    viewCore: "Core tokens",
    usesLabel: "Used for",
    groups: {
      core: "Core Colors",
      background: "Background & Surface",
      text: "Text",
      border: "Border",
      status: "Status",
      interaction: "Interaction",
      primitive: "Primitive scales",
      all: "All semantic",
    },
    labels: {
      primary: "Primary",
      secondary: "Secondary",
      accent: "Accent",
      onPrimary: "On Primary",
      onSecondary: "On Secondary",
      onAccent: "On Accent",
      primarySubtle: "Primary Subtle",
      background: "Background",
      backgroundSubtle: "Subtle Background",
      surface: "Surface",
      surfaceRaised: "Raised Surface",
      surfaceOverlay: "Overlay Surface",
      textPrimary: "Primary Text",
      textSecondary: "Secondary Text",
      textTertiary: "Tertiary Text",
      textDisabled: "Disabled Text",
      textInverse: "Inverse Text",
      textLink: "Link Text",
      borderSubtle: "Subtle Border",
      borderDefault: "Default Border",
      borderStrong: "Strong Border",
      borderFocus: "Focus Border",
      success: "Success",
      successSurface: "Success Surface",
      warning: "Warning",
      warningSurface: "Warning Surface",
      danger: "Danger",
      dangerSurface: "Danger Surface",
      info: "Info",
      infoSurface: "Info Surface",
      onSuccess: "On Success",
      onWarning: "On Warning",
      onDanger: "On Danger",
      onInfo: "On Info",
      primaryHover: "Primary Hover",
      primaryPressed: "Primary Pressed",
      primarySelected: "Primary Selected",
      secondaryHover: "Secondary Hover",
      secondaryPressed: "Secondary Pressed",
      neutralHover: "Neutral Hover",
      neutralPressed: "Neutral Pressed",
      focusRing: "Focus Ring",
      disabledSurface: "Disabled Surface",
      disabledBorder: "Disabled Border",
    },
    guides: {
      primary: {
        role: "The brand identity color. Use it for the most important actions and selections.",
        uses: "Primary CTA buttons, active tabs, key icons, checked states",
      },
      secondary: {
        role: "Supports Primary and separates a second function or information area.",
        uses: "Secondary buttons, supporting categories, secondary charts",
      },
      accent: {
        role: "Pulls attention briefly and strongly.",
        uses: "New features, emphasis badges, promotions, highlights",
      },
      surface: {
        role: "The default surface content and components sit on.",
        uses: "Cards, inputs, panels, modal interiors",
      },
      onPrimary: {
        role: "Content color on Primary. Chosen by contrast against that background, not always white.",
        uses: "Primary button text and icons",
      },
      onSecondary: {
        role: "Content color on Secondary. Chosen by contrast against that background.",
        uses: "Secondary button text and icons",
      },
      onAccent: {
        role: "Content color on Accent. Chosen by contrast against that background.",
        uses: "Accent badge and button text and icons",
      },
      primarySubtle: {
        role: "A tinted Primary used for quieter selection or emphasis.",
        uses: "Selected menu backgrounds, tags, info boxes, Primary icon backgrounds",
      },
      background: {
        role: "The outermost page or app background.",
        uses: "Body, full-screen app canvas",
      },
      backgroundSubtle: {
        role: "A softer background that divides regions inside the screen.",
        uses: "Sidebars, section backgrounds, table headers",
      },
      surfaceRaised: {
        role: "A surface that sits above the default background.",
        uses: "Cards, dropdowns, floating panels",
      },
      surfaceOverlay: {
        role: "A surface layered over the current screen.",
        uses: "Modals, dialogs, popovers, bottom sheets",
      },
      textPrimary: {
        role: "The highest-priority default text.",
        uses: "Titles, body copy, key metrics",
      },
      textSecondary: {
        role: "Supporting text with lower priority than body copy.",
        uses: "Descriptions, extra detail, metadata",
      },
      textTertiary: {
        role: "Readable information that should not compete for attention.",
        uses: "Dates, captions, help text, secondary labels",
      },
      textDisabled: {
        role: "Text for controls that cannot be used. Not just low-priority copy.",
        uses: "Disabled buttons, disabled menus, locked inputs",
      },
      textInverse: {
        role: "Reversed text for dark or strongly colored backgrounds.",
        uses: "Dark surfaces, image overlays, color banners",
      },
      textLink: {
        role: "Marks text that can be clicked or navigated.",
        uses: "Inline links, learn more, URLs",
      },
      borderSubtle: {
        role: "A light edge that separates regions without a hard divide.",
        uses: "Card dividers, list dividers, table rows",
      },
      borderDefault: {
        role: "The default outline of a component.",
        uses: "Inputs, buttons, cards",
      },
      borderStrong: {
        role: "A stronger edge for clearer separation or emphasis.",
        uses: "Selected regions, important cards, highlighted sections",
      },
      borderFocus: {
        role: "Shows the keyboard or input focus. Prefer a 2px-or-thicker focus ring.",
        uses: "Focused inputs, buttons, selects",
      },
      success: {
        role: "Success, healthy state, or completion.",
        uses: "Success icons, complete badges, success messages",
      },
      successSurface: {
        role: "A tinted background for success information.",
        uses: "Success alerts, completed card backgrounds",
      },
      warning: {
        role: "Needs attention, but is not an immediate failure.",
        uses: "Warning icons, caution badges, review-needed states",
      },
      warningSurface: {
        role: "A tinted background for warning information.",
        uses: "Warning alerts, caution boxes",
      },
      danger: {
        role: "Error, failure, deletion, or a dangerous action.",
        uses: "Delete buttons, error messages, failure badges",
      },
      dangerSurface: {
        role: "A tinted background for errors and delete warnings.",
        uses: "Error alerts, delete confirmation boxes",
      },
      info: {
        role: "Neutral guidance or reference information.",
        uses: "Help, notices, info badges",
      },
      infoSurface: {
        role: "A tinted background for notices and info boxes.",
        uses: "Help boxes, info alerts",
      },
      onSuccess: {
        role: "Text and icons on Success fills, chosen by contrast.",
        uses: "Success badges, complete buttons",
      },
      onWarning: {
        role: "Text and icons on Warning fills, chosen by contrast.",
        uses: "Warning badges, caution buttons",
      },
      onDanger: {
        role: "Text and icons on Danger fills, chosen by contrast.",
        uses: "Delete buttons, error badges",
      },
      onInfo: {
        role: "Text and icons on Info fills, chosen by contrast.",
        uses: "Info badges, notice buttons",
      },
      primaryHover: {
        role: "A Primary control with a pointer over it.",
        uses: "Primary CTA buttons, active icon buttons, Primary links",
      },
      primaryPressed: {
        role: "A Primary control being clicked or touched.",
        uses: "CTA buttons mid-click, Primary buttons mid-touch",
      },
      primarySelected: {
        role: "A Primary item that stays selected.",
        uses: "Selected tabs, active menus, selected filters and options",
      },
      secondaryHover: {
        role: "A Secondary control with a pointer over it.",
        uses: "Secondary buttons, supporting actions, Secondary icon buttons",
      },
      secondaryPressed: {
        role: "A Secondary control being clicked or touched.",
        uses: "Secondary buttons mid-click or mid-touch",
      },
      neutralHover: {
        role: "Hover for ordinary elements that do not use brand color.",
        uses: "List items, table rows, dropdown options, neutral buttons",
      },
      neutralPressed: {
        role: "A neutral element being clicked or touched.",
        uses: "List items, menus, cards, neutral icon buttons",
      },
      focusRing: {
        role: "The outline for keyboard focus or the current input target.",
        uses: "Buttons, inputs, selects, checkboxes, links",
      },
      disabledSurface: {
        role: "The inactive background of a control that cannot be used.",
        uses: "Disabled buttons, inputs, selects, toggles",
      },
      disabledBorder: {
        role: "The inactive edge of a control that cannot be used.",
        uses: "Disabled inputs, buttons, checkboxes, radios",
      },
    },
  },
  export: {
    title: "Export",
    css: "CSS",
    tailwind: "Tailwind",
    reactNative: "React Native",
    json: "JSON",
    download: "Download",
    copy: "Copy",
  },
  share: {
    title: "Share this match.",
    invalid: "This share link is damaged or incomplete.",
    back: "Back home",
  },
  notFound: {
    title: "This page isn’t a match.",
    body: "Check the address, or start again from a main color.",
    cta: "Back home",
  },
};
