export const ko = {
  meta: {
    title: "MATCHU — 색 하나만 골라. 나머지는 MATCHU가 맞춰줄게.",
    description: "기준색 하나를 넣으면 UI 전체가 그 색에 맞춰 완성됩니다.",
  },
  localeName: "한국어",
  otherLocaleName: "English",
  brand: "MATCHU",
  nav: {
    generate: "이 색으로 맞추기",
    sample: "샘플 먼저 보기",
  },
  hero: {
    taglineA: "색 하나만 골라.",
    taglineB: "나머지는 MATCHU가 맞춰줄게.",
    taglineReady: "이 색으로 맞출까?",
    doneTitle: "다 맞췄어.",
    doneBody: "이제 그대로 가져다 쓰면 돼.",
    support: "색은 장식이 아니라 결과다. 작업대는 무채색으로 두고, 선택한 색만 UI에 입힌다.",
    primaryCta: "이 색으로 맞추기",
    match: "MATCH",
    matched: "Matched",
    viewResult: "전체 결과 보기",
    sampleCta: "샘플 먼저 보기",
    chips: "웹 · 앱 · 접근성 검사 · 코드 내보내기",
    hexLabel: "Main Color",
  },
  features: {
    title: "한 색에 맞춰,\n필요한 컬러를 전부.",
    roleTitle: "역할에 맞춰",
    roleBody: "배경부터 글자까지",
    screenTitle: "화면에 맞춰",
    screenBody: "웹과 앱을 한눈에",
    readTitle: "읽기에 맞춰",
    readBody: "보기 좋고 읽기 편하게",
    codeTitle: "코드에 맞춰",
    codeBody: "그대로 복사해서 사용",
  },
  input: {
    title: "Main Color",
    subtitle: "브랜드의 기준이 되는 메인 컬러를 입력하세요.",
    step1: "Step 1",
    step1Title: "Main Color",
    step2: "Step 2",
    step2Title: "Platform",
    step2Hint: "WEB 또는 APP을 고르면 다음으로 갈 수 있어요",
    moodTitle: "어떤 느낌으로 맞출까요?",
    targetTitle: "어디에 맞출까요?",
    applyPalette: "이 팔레트로 맞추기",
    palettesTitle: "추출된 팔레트",
    advanced: "고급 옵션",
    neutral: "뉴트럴",
    secondary: "보조 컬러",
    accessibility: "대비 기준",
    cta: "이 색으로 맞추기",
    invalid: "올바른 HEX, RGB, HSL, OKLCH 값을 입력하세요.",
    moods: {
      balanced: "균형 있게",
      vivid: "선명하게",
      soft: "부드럽게",
      calm: "차분하게",
      bright: "밝게",
      highContrast: "대비 강하게",
    },
    targets: {
      web: "WEB",
      app: "APP",
      both: "WEB + APP",
    },
    neutrals: {
      pure: "완전한 회색",
      warm: "따뜻한 회색",
      cool: "차가운 회색",
      tinted: "브랜드가 섞인 회색",
    },
    secondaries: {
      monochrome: "같은 색조",
      analogous: "비슷한 색",
      split: "나란한 대비",
      complementary: "반대 색",
    },
  },
  loading: {
    title: "컬러를 맞추고 있어요",
    phrases: [
      "기준색을 읽고 있어요",
      "나머지 색을 맞추고 있어요",
      "화면에 입히고 있어요",
    ],
  },
  result: {
    title: "다 맞췄어.",
    body: "이제 그대로 가져다 쓰면 돼.",
    colors: "{count}개 컬러",
    modes: "라이트 + 다크",
    platforms: "웹 + 앱",
    contrast: "대비 오류 {count}건",
    copy: "코드 복사",
    export: "내보내기",
    save: "저장",
    share: "공유",
    saved: "프로젝트에 저장했어요",
    copied: "컬러 토큰을 복사했어요.",
    shared: "이 컬러, 같이 볼까요?",
    shareFailed: "공유 링크를 만들지 못했습니다.",
    copyFailed: "클립보드 권한이 없어 복사를 건너뜁니다.",
    fixContrast: "읽기 편하게 맞추기",
    light: "라이트",
    dark: "다크",
    web: "웹",
    app: "앱",
    matching: "컬러를 맞추고 있어요",
    palette: "팔레트",
    palettePicker: "컬러 팔레트",
    tokens: "컬러 토큰",
  },
  preview: {
    overview: "Pages",
    components: "Components",
    states: "States",
    colors: "Colors",
    screens: {
      dashboard: "Dashboard",
      marketing: "Marketing",
      form: "Form",
      data: "Data",
      feedback: "Feedback",
      home: "Home",
      list: "List",
      detail: "Detail",
      settings: "Settings",
    },
    kindPicker: "프리뷰 유형",
    kinds: {
      work: "업무 관리",
      shop: "쇼핑몰",
      finance: "금융",
      travel: "여행",
      community: "커뮤니티",
      education: "교육",
      health: "건강",
      media: "미디어",
      food: "주문·예약",
    },
    usage: "토큰 사용",
    toolbarWeb: "Web · 1440 · Fit",
    toolbarApp: "App · 390×844",
    highlightOff: "하이라이트 끄기",
    contrastOk: "대비 경고 없음",
    contrastWarn: "대비 경고 {count}건",
    mobile: {
      preview: "미리보기",
      tokens: "토큰",
      export: "내보내기",
    },
  },
  tokens: {
    title: "COLOR TOKENS",
    viewAll: "전체 토큰 보기",
    viewCore: "핵심 토큰만",
    groups: {
      core: "Core Colors",
      background: "Background & Surface",
      text: "Text",
      border: "Border",
      status: "Status",
      interaction: "Interaction",
      primitive: "Primitive scales",
      all: "All semantic",
    },
    labels: {
      primary: "Primary",
      secondary: "Secondary",
      accent: "Accent",
      onPrimary: "On Primary",
      onSecondary: "On Secondary",
      onAccent: "On Accent",
      primarySubtle: "Primary Subtle",
      background: "Background",
      backgroundSubtle: "Subtle Background",
      surface: "Surface",
      surfaceRaised: "Raised Surface",
      surfaceOverlay: "Overlay Surface",
      textPrimary: "Primary Text",
      textSecondary: "Secondary Text",
      textTertiary: "Tertiary Text",
      textDisabled: "Disabled Text",
      textInverse: "Inverse Text",
      textLink: "Link Text",
      borderSubtle: "Subtle Border",
      borderDefault: "Default Border",
      borderStrong: "Strong Border",
      borderFocus: "Focus Border",
      success: "Success",
      successSurface: "Success Surface",
      warning: "Warning",
      warningSurface: "Warning Surface",
      danger: "Danger",
      info: "Info",
      hover: "Hover",
      pressed: "Pressed",
      selected: "Selected",
      focus: "Focus",
      disabled: "Disabled",
    },
  },
  export: {
    title: "내보내기",
    css: "CSS",
    tailwind: "Tailwind",
    reactNative: "React Native",
    json: "JSON",
    download: "파일 받기",
    copy: "복사",
  },
  share: {
    title: "이 컬러, 같이 볼까요?",
    invalid: "공유 링크가 손상되었거나 만료되었습니다.",
    back: "처음으로",
  },
  notFound: {
    title: "이 페이지는 주소가 맞지 않아요",
    body: "주소를 다시 확인하거나 메인 컬러부터 다시 맞춰 보세요.",
    cta: "처음으로",
  },
};

type DeepString<T> = {
  [K in keyof T]: T[K] extends string
    ? string
    : T[K] extends readonly string[]
      ? string[]
      : T[K] extends object
        ? DeepString<T[K]>
        : T[K];
};

export type Copy = DeepString<typeof ko>;
