export const ko = {
  meta: {
    title: "MATCHU — 색 하나만 골라. 나머지는 MATCHU가 맞춰줄게.",
    description: "기준색 하나를 넣으면 UI 전체가 그 색에 맞춰 완성됩니다.",
  },
  localeName: "한국어",
  otherLocaleName: "English",
  brand: "MATCHU",
  nav: {
    generate: "이 색으로 맞추기",
    sample: "샘플 먼저 보기",
  },
  hero: {
    taglineA: "색 하나만 골라.",
    taglineB: "나머지는 MATCHU가 맞춰줄게.",
    taglineReady: "이 색으로 맞출까?",
    doneTitle: "다 맞췄어.",
    doneBody: "이제 그대로 가져다 쓰면 돼.",
    support: "색은 장식이 아니라 결과다. 작업대는 무채색으로 두고, 선택한 색만 UI에 입힌다.",
    primaryCta: "이 색으로 맞추기",
    match: "MATCH",
    matched: "Matched",
    viewResult: "전체 결과 보기",
    sampleCta: "샘플 먼저 보기",
    chips: "웹 · 앱 · 접근성 검사 · 코드 내보내기",
    hexLabel: "Main Color",
    pickHint: "저를 클릭해서 색을 선택하세요!",
    generate: "Generate",
    appleLabel: "색을 고를 사과",
  },
  features: {
    title: "한 색에 맞춰,\n필요한 컬러를 전부.",
    roleTitle: "역할에 맞춰",
    roleBody: "배경부터 글자까지",
    screenTitle: "화면에 맞춰",
    screenBody: "웹과 앱을 한눈에",
    readTitle: "읽기에 맞춰",
    readBody: "보기 좋고 읽기 편하게",
    codeTitle: "코드에 맞춰",
    codeBody: "그대로 복사해서 사용",
  },
  input: {
    title: "Main Color",
    subtitle: "브랜드의 기준이 되는 메인 컬러를 입력하세요.",
    step1: "Step 1",
    step1Title: "Main Color",
    step2: "Step 2",
    step2Title: "Platform",
    step2Hint: "WEB 또는 APP을 고르면 다음으로 갈 수 있어요",
    moodTitle: "어떤 느낌으로 맞출까요?",
    targetTitle: "어디에 맞출까요?",
    applyPalette: "이 팔레트로 맞추기",
    palettesTitle: "추출된 팔레트",
    advanced: "고급 옵션",
    neutral: "뉴트럴",
    secondary: "보조 컬러",
    accessibility: "대비 기준",
    cta: "이 색으로 맞추기",
    invalid: "올바른 HEX, RGB, HSL, OKLCH 값을 입력하세요.",
    moods: {
      balanced: "균형 있게",
      vivid: "선명하게",
      soft: "부드럽게",
      calm: "차분하게",
      bright: "밝게",
      highContrast: "대비 강하게",
    },
    targets: {
      web: "WEB",
      app: "APP",
      both: "WEB + APP",
    },
    neutrals: {
      pure: "완전한 회색",
      warm: "따뜻한 회색",
      cool: "차가운 회색",
      tinted: "브랜드가 섞인 회색",
    },
    secondaries: {
      monochrome: "같은 색조",
      analogous: "비슷한 색",
      split: "나란한 대비",
      complementary: "반대 색",
    },
  },
  loading: {
    title: "Color matching..",
    phrases: [
      "선택하신 {hex}을 분석하고 있어요.",
      "{hex} 컬러에 맞는 팔레트를 생성하고 있어요.",
      "{count}종의 컬러 팔레트가 준비되었어요.",
    ],
  },
  result: {
    title: "다 맞췄어.",
    body: "이제 그대로 가져다 쓰면 돼.",
    colors: "{count}개 컬러",
    platforms: "웹 + 앱",
    contrast: "대비 오류 {count}건",
    copy: "코드 복사",
    export: "내보내기",
    save: "저장",
    share: "공유",
    saved: "프로젝트에 저장했어요",
    copied: "컬러 토큰을 복사했어요.",
    shared: "이 컬러, 같이 볼까요?",
    shareFailed: "공유 링크를 만들지 못했습니다.",
    copyFailed: "클립보드 권한이 없어 복사를 건너뜁니다.",
    fixContrast: "읽기 편하게 맞추기",
    web: "웹",
    app: "앱",
    matching: "Color matching..",
    palette: "팔레트",
    palettePicker: "컬러 팔레트",
    tokens: "컬러 토큰",
    remake: "다시 만들기",
    remakeHint: "메인 컬러를 다시 고르기",
    remakeAppleTip: "새로운 컬러팔레트를 만들고 싶으면 저를 클릭하세요.",
    moreMenu: "더보기",
  },
  preview: {
    overview: "Page",
    components: "UI Kit",
    states: "States",
    colors: "Colors",
    screens: {
      dashboard: "Dashboard",
      marketing: "Marketing",
      form: "Form",
      data: "Data",
      feedback: "Feedback",
      home: "Home",
      list: "List",
      detail: "Detail",
      settings: "Settings",
    },
    kindPicker: "프리뷰 유형",
    kinds: {
      work: "업무 관리",
      shop: "쇼핑몰",
      finance: "금융",
      travel: "여행",
      community: "커뮤니티",
      education: "교육",
      health: "건강",
      media: "미디어",
      food: "주문·예약",
    },
    usage: "토큰 사용",
    toolbarWeb: "Web · 1440 · Fit",
    toolbarApp: "App · 390×844",
    highlightOff: "하이라이트 끄기",
    contrastOk: "대비 경고 없음",
    contrastWarn: "대비 경고 {count}건",
    mobile: {
      preview: "미리보기",
      tokens: "토큰",
      export: "내보내기",
    },
    kit: {
      actions: "액션",
      inputs: "입력",
      navigation: "탐색",
      data: "데이터",
      feedback: "피드백",
      states: "상태",
      primary: "Primary",
      other: "기타",
      fieldStates: "필드 상태",
      choices: "선택",
      tabsPager: "탭 / 경로 / 페이지",
      cardListBadge: "카드 / 목록 / 배지",
      alerts: "알림",
      hoverFocusDisabled: "호버 / 포커스 / 비활성",
      pressedFocusDisabled: "누름 / 포커스 / 비활성",
      default: "기본",
      hover: "호버",
      pressed: "누름",
      active: "활성",
      disabled: "비활성",
      loading: "로딩 중",
      secondary: "Secondary",
      tertiary: "Tertiary",
      ghost: "Ghost",
      destructive: "삭제",
      accent: "Accent",
      link: "링크",
      empty: "비어 있음",
      filled: "입력됨",
      focus: "포커스",
      error: "오류",
      textarea: "여러 줄 입력",
      checkbox: "체크박스",
      radioWeekly: "주간",
      radioMonthly: "월간",
      breadcrumb: "홈 / 라이브러리 / 노스윈드",
      all: "전체",
      inProgress: "진행",
      done: "완료",
      prev: "이전",
      next: "다음",
      pageOf: "{page} / {total}쪽",
      chipCalm: "차분",
      chipVivid: "선명",
      emptyState: "아직 항목이 없어요",
      success: "성공",
      successBody: "저장했습니다.",
      warning: "경고",
      warningBody: "확인이 필요합니다.",
      errorTitle: "오류",
      errorBody: "다시 시도하세요.",
      info: "안내",
      infoBody: "상태색은 팔레트와 분리합니다.",
      lastAction: "마지막 동작: {action}",
      idle: "버튼을 눌러 상태를 확인하세요",
      saved: "저장했어요",
      deleted: "삭제했어요",
      linked: "링크로 이동했어요",
      switchOn: "켜짐",
      switchOff: "꺼짐",
      tabAll: "전체 {count}개",
      tabActive: "진행 {count}개",
      tabDone: "완료 {count}개",
      notify: "알림 받기",
      openModal: "모달 열기",
      modalTitle: "작업을 확정할까요?",
      modalBody: "Primary 버튼은 이 화면의 핵심 행동에만 씁니다.",
      cancel: "닫기",
      confirm: "확인",
      help: "도움말",
      helpTip: "Accent는 면적의 5–10%만 사용하세요.",
      formControls: "입력 컴포넌트",
      selectionControls: "선택 컴포넌트",
      disableFields: "필드 비활성화",
      loginTitle: "로그인",
      loginDescription: "이메일 계정으로 서비스를 시작하세요.",
      loginEmail: "이메일 아이디",
      loginIdPlaceholder: "아이디",
      loginIdError: "영문, 숫자, 마침표, 밑줄만 입력하세요.",
      emailDomain: "메일 주소",
      domainCustom: "직접 입력",
      customDomainPlaceholder: "메일 주소 직접 입력",
      emailDomainError: "올바른 메일 주소를 입력하세요.",
      loginEmailHint: "아이디와 메일 주소를 선택하세요.",
      loginPassword: "비밀번호",
      passwordPlaceholder: "비밀번호 입력",
      passwordRule: "8–16자 영문, 숫자, 특수문자를 모두 포함하세요.",
      passwordError: "비밀번호 규칙을 충족하지 못했습니다.",
      login: "로그인",
      loggingIn: "로그인 중",
      loggedIn: "완료",
      loginReset: "다시 입력",
      loginSuccess: "로그인되었습니다.",
      plan: "플랜",
      selectPlaceholder: "플랜 선택",
      selectError: "플랜을 하나 선택하세요.",
      selectHint: "열어서 옵션과 선택 상태를 확인하세요.",
      planStarter: "스타터",
      planTeam: "팀",
      planBusiness: "비즈니스",
      notePlaceholder: "10자 이상 메모를 입력하세요.",
      noteError: "메모를 10자 이상 입력하세요.",
      noteHint: "입력창 크기와 포커스 상태를 확인하세요.",
      acceptTerms: "이용 약관에 동의",
      checked: "선택됨",
      unchecked: "선택 안 됨",
      radio: "라디오",
      switch: "스위치",
      accessibility: "ACCESSIBILITY",
      accessibilityTitle: "접근성 설정",
      accessibilityBody: "보기 편한 화면과 모션을 직접 조절해 보세요.",
      nightMode: "나이트 모드",
      fontSize: "글자 크기",
      fontSmall: "작게",
      fontMedium: "보통",
      fontLarge: "크게",
      fontSample: "MATCHU로 컬러팔레트 맞춰!",
      motionSettings: "모션 설정",
      appleMotion: "사과 점프 모션",
      appleBlink: "눈 깜빡임",
      applePreview: "사과 모션 미리보기",
      chatTitle: "상담 채팅",
      chatStatus: "응답 가능",
      chatGreeting: "안녕하세요. 편하게 말씀해 주세요.",
      chatPlaceholder: "메시지를 입력하세요",
      chatSend: "메시지 보내기",
      chatTyping: "답변을 입력하고 있어요…",
      chatReplies: [
        "그러시군요.",
        "말씀해 주셔서 감사합니다.",
        "네, 이해했어요.",
        "그 부분을 조금 더 들려주실래요?",
        "그렇게 생각하시는군요.",
        "계속 말씀해 주세요.",
      ],
      searchPlaceholder: "검색어 입력",
      searchOptions: ["디자인 시스템", "컬러 팔레트", "UI 컴포넌트", "프로토타입"],
      noSearchResults: "검색 결과가 없습니다.",
      multiSelect: "관심 분야",
      multiSelectPlaceholder: "분야 선택",
      multiSelectCount: "{n}개 선택됨",
      multiSelectDesign: "디자인",
      multiSelectDevelopment: "개발",
      multiSelectMarketing: "마케팅",
      multiSelectResearch: "리서치",
      quantity: "수량",
      decreaseQuantity: "수량 줄이기",
      increaseQuantity: "수량 늘리기",
      rating: "별점",
      slider: "슬라이더",
      feedbackActions: "피드백 · 오버레이 동작",
      actionConfirmModal: "Modal",
      actionDrawer: "Drawer",
      actionPopover: "Popover",
      actionTooltip: "Tooltip",
      actionLoading: "Loading Overlay",
      successAlertTitle: "저장 완료",
      successAlertBody: "변경사항이 안전하게 저장되었습니다.",
      infoAlertTitle: "새로운 안내",
      infoAlertBody: "확인할 수 있는 새 정보가 있습니다.",
      warningAlertTitle: "확인이 필요해요",
      warningAlertBody: "계속하기 전에 입력 내용을 확인하세요.",
      errorAlertTitle: "처리하지 못했어요",
      errorAlertBody: "잠시 후 다시 시도해 주세요.",
      confirmModalTitle: "변경사항을 적용할까요?",
      confirmModalBody: "선택한 설정이 현재 화면에 반영됩니다.",
      drawerTitle: "세부 설정",
      drawerBody: "이 패널에서 추가 옵션과 세부 정보를 확인할 수 있습니다.",
      popoverTitle: "빠른 도움말",
      popoverBody: "Popover는 현재 맥락을 유지한 채 짧은 정보를 보여줍니다.",
      tooltipBody: "버튼 위에 표시되는 짧은 설명입니다.",
      loadingBody: "처리하고 있어요…",
      close: "닫기",
      dataCharts: "데이터 차트",
      barChart: "주간 활동",
      chartCaption: "막대를 선택해 값을 확인하세요.",
      chartLabels: ["검색", "가입", "활성", "결제", "재방문"],
      selectableTable: "선택 가능한 데이터 테이블",
      tableTitle: "최근 프로젝트",
      tableCaption: "행을 선택하거나 헤더를 정렬해 보세요.",
      tableSelected: "선택됨",
      tableSelect: "행 선택",
      tableName: "프로젝트",
      tableOwner: "담당자",
      tableStatus: "상태",
      tableAmount: "점수",
      tableItems: ["브랜드 개편", "모바일 앱", "결제 개선", "리서치", "보관 프로젝트"],
      tableOwners: ["민준", "서연", "지우", "하준", "예린"],
      tableStatusLabels: ["완료", "진행 중", "검토", "지연", "비활성"],
      extendedKit: {
        title: "상태 · 탐색 · 데이터 입력",
        badges: "Badge · Chip · Tag",
        complete: "완료",
        inProgress: "진행 중",
        review: "검토 필요",
        delayed: "지연",
        design: "디자인",
        development: "개발",
        marketing: "마케팅",
        tag: "컬러 토큰",
        removeTag: "태그 제거",
        restoreTag: "태그 다시 추가",
        tabsSegments: "Tabs · Segmented Control",
        overview: "개요",
        activity: "활동",
        settings: "설정",
        overviewBody: "서비스의 핵심 정보를 확인합니다.",
        activityBody: "최근 변경과 사용자 활동을 확인합니다.",
        settingsBody: "표시 방식과 알림을 설정합니다.",
        weekly: "주간",
        monthly: "월간",
        yearly: "연간",
        loadingStates: "Progress · Skeleton · Spinner",
        uploadProgress: "업로드 진행률",
        advance: "진행 상태 변경",
        loading: "데이터를 불러오는 중",
        skeleton: "콘텐츠 로딩 미리보기",
        emptyStates: "Empty State",
        empty: "비어 있음",
        noResults: "검색 결과 없음",
        error: "오류",
        emptyTitle: "아직 항목이 없어요",
        emptyBody: "새 항목을 추가하면 이곳에 표시됩니다.",
        noResultsTitle: "검색 결과가 없어요",
        noResultsBody: "검색어나 필터를 변경해 보세요.",
        errorTitle: "불러오지 못했어요",
        errorBody: "잠시 후 다시 시도해 주세요.",
        retry: "다시 시도",
        addItem: "항목 추가",
        accordion: "Accordion",
        accordionTokens: "컬러 토큰",
        accordionTokensBody: "역할에 따라 Primary, Surface, Text 토큰을 사용합니다.",
        accordionComponents: "컴포넌트",
        accordionComponentsBody: "동일한 상태와 상호작용 규칙을 공유합니다.",
        accordionAccessibility: "접근성",
        accordionAccessibilityBody: "키보드 포커스와 충분한 대비를 유지합니다.",
        navigation: "Pagination · Breadcrumb",
        breadcrumb: "현재 경로",
        home: "홈",
        library: "라이브러리",
        current: "UI Kit",
        page: "{n}페이지를 보고 있어요",
        pagination: "페이지 이동",
        previous: "이전 페이지",
        next: "다음 페이지",
        dateTime: "Date · Time Picker",
        date: "날짜",
        time: "시간",
        disabledDate: "비활성 날짜",
        fileUpload: "File Upload",
        dropFile: "파일을 끌어 놓거나 선택하세요",
        uploadHint: "이미지 또는 PDF · 최대 2MB",
        uploadComplete: "업로드 준비 완료",
        uploadError: "지원하지 않는 파일이에요",
        avatarList: "Avatar · List Item",
        memberOne: "민경",
        memberTwo: "지수",
        memberThree: "하윤",
        designer: "프로덕트 디자이너",
        developer: "프론트엔드 개발자",
        marketer: "마케터",
        menus: "Dropdown · Context Menu",
        actions: "작업 메뉴",
        edit: "편집",
        duplicate: "복제",
        archive: "보관 · 비활성",
        contextTarget: "프로젝트 문서.pdf",
        contextHint: "영역을 우클릭해 보세요.",
        open: "열기",
        rename: "이름 변경",
        delete: "삭제",
        close: "닫기",
      },
    },
    buttons: {
      color: "컬러 버튼",
      soft: "소프트 버튼",
      outline: "아웃라인 버튼",
      neutral: "Neutral",
      primary: "Primary",
      secondary: "Secondary",
      accent: "Accent",
      info: "Info",
      success: "Success",
      warning: "Warning",
      error: "Error",
    },
    gallery: {
      shoes: "신발",
      bags: "가방",
      hoodies: "후디",
      accessories: "소품",
      sale: "세일",
      find: "찾기",
      productTitle: "데일리 스니커",
      reviews: "리뷰 {count}개",
      meeting: "팀 싱크",
      meetingBody: "디자인·개발 주간 리뷰",
      hour: "1시간",
      priceRange: "가격대",
      salesNote: "이번 주 매출이 지난주보다 15% 올랐어요.",
      charts: "차트",
      details: "상세",
      pageScore: "페이지 점수",
      allGood: "이상 없음",
      recentOrders: "최근 주문",
      send: "전송",
      failed: "실패",
      progressing: "진행 중",
      completed: "완료",
      revenue: "9월 매출",
      moreThanLast: "지난달보다 {n}% 높아요",
      newPost: "새 글 쓰기",
      addFiles: "파일 추가",
      remaining: "{n}자 남음",
      draft: "임시저장",
      publish: "발행",
      chatName: "민준",
      chatA: "오늘 팔레트 확정했어요.",
      chatB: "Primary는 버튼에만 쓸게요.",
      delivered: "전송됨",
      playerTitle: "오후 작업 플레이리스트",
      playerSub: "포커스 2시간",
      messages: "새 메시지 {n}개",
      verified: "인증이 끝났어요",
      verifyEmail: "이메일 인증하기",
      denied: "접근 거부",
      support: "지원",
      signupTitle: "계정 만들기",
      signupBody: "가입은 무료고 1분이면 끝나요.",
      email: "이메일",
      password: "비밀번호",
      passwordHint: "비밀번호는 8자 이상이어야 해요.",
      acceptTerms: "약관에 동의",
      subscribe: "업데이트 받기",
      register: "가입",
      orLogin: "또는 로그인",
      planTitle: "스타터 플랜",
      perMonth: "월 {price}",
      featureA: "하루 토큰 20개",
      featureB: "프로젝트 10개",
      featureC: "API 접근",
      buy: "구매하기",
      admin: "관리",
      products: "상품",
      users: "사용자",
      settings: "설정",
      heroKicker: "노스윈드",
      heroTitle: "이번 주말, 뭐 배워볼까",
      heroBody: "색이 정해지면 화면이 따라옵니다.",
      crumbHome: "홈",
      crumbLib: "라이브러리",
      crumbNow: "노스윈드",
      faqShip: "배송은 얼마나 걸려요?",
      faqShipBody: "서울은 다음날, 그 외는 2–3일이에요.",
      faqReturn: "교환은 어떻게 하나요?",
      faqReturnBody: "수령 후 7일 안에 신청하면 돼요.",
      collapseMore: "자세히",
      collapseBody: "Primary는 한 화면의 핵심 행동에만 씁니다.",
      countLeft: "마감까지",
      diffBefore: "이전",
      diffAfter: "이후",
      drawerOpen: "메뉴",
      drawerInbox: "받은편지함",
      drawerTeam: "팀",
      dropSort: "정렬",
      dropNew: "최신순",
      dropOld: "오래된순",
      fabNote: "메모",
      fabUpload: "올리기",
      legendProfile: "프로필",
      filePick: "파일 선택",
      city: "도시",
      seoul: "서울",
      busan: "부산",
      otp: "인증번호",
      footerDocs: "문서",
      footerBlog: "블로그",
      footerCopy: "© MATCHU",
      toastOn: "토스트 보기",
      toastBody: "저장했습니다.",
      rateThis: "이 상품을 평가하세요",
      stepCart: "담기",
      stepPay: "결제",
      stepDone: "완료",
      swapOn: "켜짐",
      swapOff: "꺼짐",
      rowA: "스니커",
      rowB: "후디",
      qty: "수량",
      rotateA: "팔레트를 고르고",
      rotateB: "화면에 입히고",
      rotateC: "코드로 가져가세요",
      eventPlan: "기획",
      eventBuild: "제작",
      eventShip: "배포",
      online: "온라인",
      away: "자리비움",
      offline: "오프라인",
      shortcut: "저장",
      searchJoin: "검색",
      codeSample: "const theme = tokens",
      phoneApp: "MATCHU",
      windowTitle: "미리보기",
      megaShop: "쇼핑",
      megaNew: "신상",
      megaSale: "세일",
      listUnread: "읽지 않음",
      listStar: "중요",
      maskNote: "마스크",
      skelWait: "불러오는 중",
      upload: "업로드",
      linkDocs: "문서 보기",
      homeDock: "홈",
    },
  },
  tokens: {
    title: "COLOR TOKENS",
    viewAll: "전체 토큰",
    viewCore: "핵심 토큰",
    resetAll: "변경한 토큰 모두 초기화",
    usesLabel: "주요 적용",
    groups: {
      core: "Core Colors",
      background: "Background & Surface",
      text: "Text",
      border: "Border",
      status: "Status",
      interaction: "Interaction",
      primitive: "Primitive scales",
      all: "All semantic",
    },
    labels: {
      primary: "Primary",
      secondary: "Secondary",
      accent: "Accent",
      onPrimary: "On Primary",
      onSecondary: "On Secondary",
      onAccent: "On Accent",
      primarySubtle: "Primary Subtle",
      background: "Background",
      backgroundSubtle: "Subtle Background",
      surface: "Surface",
      surfaceRaised: "Raised Surface",
      surfaceOverlay: "Overlay Surface",
      textPrimary: "Primary Text",
      textSecondary: "Secondary Text",
      textTertiary: "Tertiary Text",
      textDisabled: "Disabled Text",
      textInverse: "Inverse Text",
      textLink: "Link Text",
      borderSubtle: "Subtle Border",
      borderDefault: "Default Border",
      borderStrong: "Strong Border",
      borderFocus: "Focus Border",
      success: "Success",
      successSurface: "Success Surface",
      warning: "Warning",
      warningSurface: "Warning Surface",
      danger: "Danger",
      dangerSurface: "Danger Surface",
      info: "Info",
      infoSurface: "Info Surface",
      onSuccess: "On Success",
      onWarning: "On Warning",
      onDanger: "On Danger",
      onInfo: "On Info",
      primaryHover: "Primary Hover",
      primaryPressed: "Primary Pressed",
      primarySelected: "Primary Selected",
      secondaryHover: "Secondary Hover",
      secondaryPressed: "Secondary Pressed",
      neutralHover: "Neutral Hover",
      neutralPressed: "Neutral Pressed",
      focusRing: "Focus Ring",
      disabledSurface: "Disabled Surface",
      disabledBorder: "Disabled Border",
    },
    guides: {
      primary: {
        role: "서비스의 정체성을 나타내는 대표 색상. 가장 중요한 행동과 선택을 강조합니다.",
        uses: "주요 CTA 버튼, 활성 탭, 핵심 아이콘, 체크 상태",
      },
      secondary: {
        role: "Primary를 보조하면서 별도의 기능이나 정보 영역을 구분합니다.",
        uses: "보조 버튼, 보조 카테고리, 서브 그래프",
      },
      accent: {
        role: "사용자의 시선을 짧고 강하게 끌어야 하는 요소에 사용합니다.",
        uses: "신규 기능, 강조 배지, 프로모션, 하이라이트",
      },
      surface: {
        role: "콘텐츠나 컴포넌트가 놓이는 기본 바탕색입니다.",
        uses: "카드, 입력 필드, 패널, 모달 내부",
      },
      onPrimary: {
        role: "Primary 색상 위에 올라가는 콘텐츠 색상입니다. 배경과의 명도 대비를 기준으로 결정합니다.",
        uses: "Primary 버튼의 텍스트·아이콘",
      },
      onSecondary: {
        role: "Secondary 색상 위에 올라가는 콘텐츠 색상입니다. 배경과의 명도 대비를 기준으로 결정합니다.",
        uses: "Secondary 버튼의 텍스트·아이콘",
      },
      onAccent: {
        role: "Accent 색상 위에 올라가는 콘텐츠 색상입니다. 배경과의 명도 대비를 기준으로 결정합니다.",
        uses: "Accent 배지·버튼의 텍스트와 아이콘",
      },
      primarySubtle: {
        role: "Primary를 옅게 사용하여 강하지 않은 선택·강조 상태를 표현합니다.",
        uses: "선택된 메뉴 배경, 태그, 정보 박스, Primary 아이콘 배경",
      },
      background: {
        role: "페이지나 앱 화면 전체의 가장 바깥쪽 배경입니다.",
        uses: "body, 앱 전체 화면",
      },
      backgroundSubtle: {
        role: "화면 안에서 영역을 부드럽게 구분하는 보조 배경입니다.",
        uses: "사이드바, 섹션 배경, 테이블 헤더",
      },
      surfaceRaised: {
        role: "기본 배경보다 위에 떠 있는 것처럼 보이는 표면입니다.",
        uses: "카드, 드롭다운, 플로팅 패널",
      },
      surfaceOverlay: {
        role: "현재 화면 위에 겹쳐서 나타나는 콘텐츠의 표면입니다.",
        uses: "모달, 다이얼로그, 팝오버, 바텀시트",
      },
      textPrimary: {
        role: "가장 높은 우선순위의 기본 텍스트입니다.",
        uses: "제목, 본문, 핵심 수치",
      },
      textSecondary: {
        role: "본문보다 중요도가 낮은 보조 텍스트입니다.",
        uses: "설명, 부가 정보, 메타데이터",
      },
      textTertiary: {
        role: "읽을 수는 있어야 하지만 강조할 필요가 적은 정보입니다.",
        uses: "날짜, 캡션, 도움말, 보조 레이블",
      },
      textDisabled: {
        role: "사용할 수 없거나 비활성화된 요소의 텍스트입니다. 중요도가 낮은 텍스트가 아닙니다.",
        uses: "비활성 버튼, 비활성 메뉴, 입력 불가 항목",
      },
      textInverse: {
        role: "어두운색 또는 강한 색상의 배경 위에 사용하는 반전 텍스트입니다.",
        uses: "다크 배경, 이미지 오버레이, 컬러 배너",
      },
      textLink: {
        role: "클릭 또는 이동할 수 있는 텍스트임을 나타냅니다.",
        uses: "텍스트 링크, 자세히 보기, URL",
      },
      borderSubtle: {
        role: "강한 구분 없이 영역이나 항목의 경계를 가볍게 표현합니다.",
        uses: "카드 구분선, 리스트 디바이더, 테이블 행",
      },
      borderDefault: {
        role: "컴포넌트의 기본 윤곽을 명확하게 표현합니다.",
        uses: "입력 필드, 버튼, 카드",
      },
      borderStrong: {
        role: "보다 확실한 구분이나 강조가 필요한 경계입니다.",
        uses: "선택 영역, 중요한 카드, 강조 구획",
      },
      borderFocus: {
        role: "키보드나 입력 포커스가 위치한 요소를 표시합니다. 일반 테두리와 구분되는 2px 이상 포커스 링이 좋습니다.",
        uses: "포커스된 입력 필드, 버튼, 셀렉트",
      },
      success: {
        role: "작업 성공, 정상 상태, 완료를 표현합니다.",
        uses: "성공 아이콘, 완료 배지, 성공 메시지",
      },
      successSurface: {
        role: "성공 정보를 담는 영역의 옅은 배경입니다.",
        uses: "성공 알림, 완료 카드 배경",
      },
      warning: {
        role: "주의가 필요하지만 즉각적인 실패는 아닌 상태입니다.",
        uses: "경고 아이콘, 주의 배지, 검토 필요 상태",
      },
      warningSurface: {
        role: "경고 정보를 담는 영역의 옅은 배경입니다.",
        uses: "경고 알림, 주의 안내 박스",
      },
      danger: {
        role: "오류, 실패, 삭제, 위험한 행동을 표현합니다.",
        uses: "삭제 버튼, 오류 메시지, 실패 배지",
      },
      dangerSurface: {
        role: "오류 메시지·삭제 경고 영역의 옅은 배경입니다.",
        uses: "오류 알림, 삭제 확인 박스",
      },
      info: {
        role: "중립적인 안내나 참고 정보를 표현합니다.",
        uses: "도움말, 안내 메시지, 정보 배지",
      },
      infoSurface: {
        role: "안내 메시지·정보 박스의 옅은 배경입니다.",
        uses: "도움말 박스, 안내 알림",
      },
      onSuccess: {
        role: "Success 배경 위에 올리는 텍스트·아이콘 색상입니다. 대비를 기준으로 결정합니다.",
        uses: "성공 배지, 완료 버튼",
      },
      onWarning: {
        role: "Warning 배경 위에 올리는 텍스트·아이콘 색상입니다. 대비를 기준으로 결정합니다.",
        uses: "경고 배지, 주의 버튼",
      },
      onDanger: {
        role: "Danger 배경 위에 올리는 텍스트·아이콘 색상입니다. 대비를 기준으로 결정합니다.",
        uses: "삭제 버튼, 오류 배지",
      },
      onInfo: {
        role: "Info 배경 위에 올리는 텍스트·아이콘 색상입니다. 대비를 기준으로 결정합니다.",
        uses: "정보 배지, 안내 버튼",
      },
      primaryHover: {
        role: "Primary 요소에 포인터가 올라간 상태를 표현합니다.",
        uses: "주요 CTA 버튼, 활성 아이콘 버튼, Primary 링크",
      },
      primaryPressed: {
        role: "Primary 요소를 클릭하거나 터치하고 있는 순간을 표현합니다.",
        uses: "클릭 중인 CTA 버튼, 터치 중인 Primary 버튼",
      },
      primarySelected: {
        role: "Primary 성격의 항목이 선택되어 유지되는 상태를 표현합니다.",
        uses: "선택된 탭, 활성 메뉴, 선택된 필터·옵션",
      },
      secondaryHover: {
        role: "Secondary 요소에 포인터가 올라간 상태를 표현합니다.",
        uses: "보조 버튼, 보조 액션, Secondary 아이콘 버튼",
      },
      secondaryPressed: {
        role: "Secondary 요소를 클릭하거나 터치하고 있는 순간을 표현합니다.",
        uses: "클릭 중인 보조 버튼, 터치 중인 Secondary 버튼",
      },
      neutralHover: {
        role: "브랜드 색상을 사용하지 않는 일반 요소의 마우스 오버 상태를 표현합니다.",
        uses: "리스트 항목, 테이블 행, 드롭다운 옵션, 중립 버튼",
      },
      neutralPressed: {
        role: "일반 요소를 클릭하거나 터치하고 있는 순간을 표현합니다.",
        uses: "리스트 항목, 메뉴, 카드, 중립 아이콘 버튼",
      },
      focusRing: {
        role: "키보드 탐색 또는 입력 대상이 된 요소의 외곽선을 표시합니다.",
        uses: "버튼, 입력 필드, 셀렉트, 체크박스, 링크",
      },
      disabledSurface: {
        role: "조작할 수 없는 컴포넌트의 비활성 배경을 표현합니다.",
        uses: "비활성 버튼, 입력 필드, 셀렉트, 토글",
      },
      disabledBorder: {
        role: "조작할 수 없는 컴포넌트의 비활성 경계를 표현합니다.",
        uses: "비활성 입력 필드, 버튼, 체크박스, 라디오 버튼",
      },
    },
  },
  export: {
    title: "내보내기",
    css: "CSS",
    tailwind: "Tailwind",
    reactNative: "React Native",
    json: "JSON",
    download: "파일 받기",
    copy: "복사",
  },
  share: {
    title: "이 컬러, 같이 볼까요?",
    invalid: "공유 링크가 손상되었거나 만료되었습니다.",
    back: "처음으로",
  },
  notFound: {
    title: "이 페이지는 주소가 맞지 않아요",
    body: "주소를 다시 확인하거나 메인 컬러부터 다시 맞춰 보세요.",
    cta: "처음으로",
  },
};

type DeepString<T> = {
  [K in keyof T]: T[K] extends string
    ? string
    : T[K] extends readonly string[]
      ? string[]
      : T[K] extends object
        ? DeepString<T[K]>
        : T[K];
};

export type Copy = DeepString<typeof ko>;
