export type CoreToken = {
  key: string;
  group: string;
  path: string;
};

export const CORE_TOKENS: CoreToken[] = [
  { key: "primary", group: "core", path: "primary.default" },
  { key: "secondary", group: "core", path: "secondary.default" },
  { key: "accent", group: "core", path: "accent.default" },
  { key: "onPrimary", group: "core", path: "primary.onPrimary" },
  { key: "primarySubtle", group: "core", path: "primary.subtle" },
  { key: "background", group: "background", path: "background.canvas" },
  { key: "backgroundSubtle", group: "background", path: "background.subtle" },
  { key: "surface", group: "background", path: "surface.default" },
  { key: "surfaceRaised", group: "background", path: "surface.raised" },
  { key: "surfaceOverlay", group: "background", path: "surface.overlay" },
  { key: "textPrimary", group: "text", path: "text.primary" },
  { key: "textSecondary", group: "text", path: "text.secondary" },
  { key: "textTertiary", group: "text", path: "text.tertiary" },
  { key: "textDisabled", group: "text", path: "text.disabled" },
  { key: "textInverse", group: "text", path: "text.inverse" },
  { key: "textLink", group: "text", path: "text.link" },
  { key: "borderSubtle", group: "border", path: "border.subtle" },
  { key: "borderDefault", group: "border", path: "border.default" },
  { key: "borderStrong", group: "border", path: "border.strong" },
  { key: "borderFocus", group: "border", path: "border.focus" },
  { key: "success", group: "status", path: "success.default" },
  { key: "successSurface", group: "status", path: "success.surface" },
  { key: "warning", group: "status", path: "warning.default" },
  { key: "warningSurface", group: "status", path: "warning.surface" },
  { key: "danger", group: "status", path: "danger.default" },
  { key: "info", group: "status", path: "info.default" },
  { key: "hover", group: "interaction", path: "interaction.hover" },
  { key: "pressed", group: "interaction", path: "interaction.pressed" },
  { key: "selected", group: "interaction", path: "interaction.selected" },
  { key: "focus", group: "interaction", path: "interaction.focusRing" },
  { key: "disabled", group: "interaction", path: "interaction.disabledForeground" },
];

export const TOKEN_USES: Record<string, string> = {
  "primary.default": "Primary button, key action",
  "secondary.default": "Secondary button, supporting action",
  "accent.default": "Badge, chart point, small emphasis",
  "background.canvas": "Page and app canvas",
  "background.subtle": "Sectioned secondary background",
  "surface.default": "Cards, panels, sheets",
  "surface.raised": "Dropdown, floating card",
  "surface.overlay": "Modal, popover, bottom sheet",
  "text.primary": "Titles and body",
  "text.secondary": "Supporting and meta text",
  "text.tertiary": "Low-emphasis labels",
  "text.disabled": "Disabled labels",
  "text.inverse": "Text on inverse surfaces",
  "text.link": "Inline links",
  "border.subtle": "Card edges and dividers",
  "border.default": "Inputs and default outlines",
  "border.strong": "Emphasized separators",
  "border.focus": "Keyboard focus ring",
  "success.default": "Success icon and solid badge",
  "warning.default": "Warning icon and solid badge",
  "danger.default": "Error and destructive action",
  "info.default": "Neutral system information",
  "interaction.hover": "Hover wash",
  "interaction.pressed": "Pressed wash",
  "interaction.selected": "Selected row or chip",
  "interaction.focusRing": "Focus outline",
  "interaction.disabledForeground": "Disabled icon and text",
};
