export type CoreToken = {
  key: string;
  group: string;
  path: string;
};

export const CORE_TOKENS: CoreToken[] = [
  { key: "primary", group: "core", path: "primary.default" },
  { key: "secondary", group: "core", path: "secondary.default" },
  { key: "accent", group: "core", path: "accent.default" },
  { key: "surface", group: "core", path: "surface.default" },
  { key: "onPrimary", group: "core", path: "primary.onPrimary" },
  { key: "onSecondary", group: "core", path: "secondary.onSecondary" },
  { key: "onAccent", group: "core", path: "accent.onAccent" },
  { key: "primarySubtle", group: "core", path: "primary.subtle" },
  { key: "background", group: "background", path: "background.canvas" },
  { key: "backgroundSubtle", group: "background", path: "background.subtle" },
  { key: "surfaceRaised", group: "background", path: "surface.raised" },
  { key: "surfaceOverlay", group: "background", path: "surface.overlay" },
  { key: "textPrimary", group: "text", path: "text.primary" },
  { key: "textSecondary", group: "text", path: "text.secondary" },
  { key: "textTertiary", group: "text", path: "text.tertiary" },
  { key: "textDisabled", group: "text", path: "text.disabled" },
  { key: "textInverse", group: "text", path: "text.inverse" },
  { key: "textLink", group: "text", path: "text.link" },
  { key: "borderSubtle", group: "border", path: "border.subtle" },
  { key: "borderDefault", group: "border", path: "border.default" },
  { key: "borderStrong", group: "border", path: "border.strong" },
  { key: "borderFocus", group: "border", path: "border.focus" },
  { key: "success", group: "status", path: "success.default" },
  { key: "successSurface", group: "status", path: "success.surface" },
  { key: "warning", group: "status", path: "warning.default" },
  { key: "warningSurface", group: "status", path: "warning.surface" },
  { key: "danger", group: "status", path: "danger.default" },
  { key: "dangerSurface", group: "status", path: "danger.surface" },
  { key: "info", group: "status", path: "info.default" },
  { key: "infoSurface", group: "status", path: "info.surface" },
  { key: "onSuccess", group: "status", path: "success.onSuccess" },
  { key: "onWarning", group: "status", path: "warning.onWarning" },
  { key: "onDanger", group: "status", path: "danger.onDanger" },
  { key: "onInfo", group: "status", path: "info.onInfo" },
  { key: "primaryHover", group: "interaction", path: "interaction.primaryHover" },
  { key: "primaryPressed", group: "interaction", path: "interaction.primaryPressed" },
  { key: "primarySelected", group: "interaction", path: "interaction.primarySelected" },
  { key: "secondaryHover", group: "interaction", path: "interaction.secondaryHover" },
  { key: "secondaryPressed", group: "interaction", path: "interaction.secondaryPressed" },
  { key: "neutralHover", group: "interaction", path: "interaction.neutralHover" },
  { key: "neutralPressed", group: "interaction", path: "interaction.neutralPressed" },
  { key: "focusRing", group: "interaction", path: "interaction.focusRing" },
  { key: "disabledSurface", group: "interaction", path: "interaction.disabledSurface" },
  { key: "disabledBorder", group: "interaction", path: "interaction.disabledBorder" },
  ...["primary", "secondary", "accent"].flatMap(role => ["onHover", "onPressed", "selectedBorder", "selectedText", "selectedIcon", "disabled", "disabledText"].map(state => ({ key: `${role}${state[0].toUpperCase()}${state.slice(1)}`, group: "interaction", path: `action.${role}.${state}` }))),
  { key: "accentHover", group: "interaction", path: "accent.hover" },
  { key: "accentPressed", group: "interaction", path: "accent.pressed" },
  ...["success", "warning", "danger", "info"].flatMap(role => ["surfaceStrong", "border", "text", "icon", "hover", "pressed", "onHover", "onPressed", "disabled", "disabledText"].map(state => ({ key: `${role}${state[0].toUpperCase()}${state.slice(1)}`, group: "status", path: `status.${role}.${state}` }))),
];

export const TOKEN_USES: Record<string, string> = {
  "primary.default": "Primary button background (input color)",
  "primary.hover": "Adaptive primary hover",
  "primary.pressed": "Adaptive primary pressed",
  "primary.onPrimary": "Primary button text (On Primary)",
  "secondary.default": "Secondary button, supporting action",
  "accent.default": "Badge, chart point, small emphasis",
  "surface.default": "Cards, inputs, sheets",
  "secondary.onSecondary": "Text on secondary fills",
  "accent.onAccent": "Text on accent fills",
  "background.canvas": "Page and app canvas",
  "background.subtle": "Sectioned secondary background",
  "surface.raised": "Dropdown, floating card",
  "surface.overlay": "Modal, popover, bottom sheet",
  "text.primary": "Titles and body",
  "text.secondary": "Supporting and meta text",
  "text.tertiary": "Low-emphasis labels",
  "text.disabled": "Disabled labels",
  "text.inverse": "Text on inverse surfaces",
  "text.link": "Inline links",
  "border.subtle": "Card edges and dividers",
  "border.default": "Inputs and default outlines",
  "border.strong": "Emphasized separators",
  "border.focus": "Keyboard focus ring",
  "success.default": "Success icon and solid badge",
  "success.surface": "Success alert background",
  "warning.default": "Warning icon and solid badge",
  "warning.surface": "Warning alert background",
  "danger.default": "Error and destructive action",
  "danger.surface": "Error and delete warning background",
  "info.default": "Neutral system information",
  "info.surface": "Help and notice background",
  "success.onSuccess": "Text on success fills",
  "warning.onWarning": "Text on warning fills",
  "danger.onDanger": "Text on danger fills",
  "info.onInfo": "Text on info fills",
  "interaction.primaryHover": "Primary hover",
  "interaction.primaryPressed": "Primary pressed",
  "interaction.primarySelected": "Primary selected",
  "interaction.secondaryHover": "Secondary hover",
  "interaction.secondaryPressed": "Secondary pressed",
  "interaction.neutralHover": "Neutral hover",
  "interaction.neutralPressed": "Neutral pressed",
  "interaction.focusRing": "Focus outline",
  "interaction.disabledSurface": "Disabled background",
  "interaction.disabledBorder": "Disabled border",
};
