import type { SemanticTokens } from "@/lib/color-engine/types";
import type { PaletteTokens } from "./types";

export function applyGeneratedToSemantic(
  semantic: SemanticTokens,
  tokens: PaletteTokens,
): SemanticTokens {
  return {
    ...semantic,
    action: tokens.system.actions,
    status: tokens.system.statuses,
    selected: { background: tokens.system.actions.primary.selected, border: tokens.system.actions.primary.selectedBorder, text: tokens.system.actions.primary.selectedText, icon: tokens.system.actions.primary.selectedIcon },
    focus: { ring: tokens.interaction.focusRing },
    disabled: { background: tokens.interaction.disabledSurface, border: tokens.interaction.disabledBorder, text: tokens.text.disabled, icon: tokens.text.disabled },
    background: {
      ...semantic.background,
      canvas: tokens.backgroundAndSurface.background,
      subtle: tokens.backgroundAndSurface.subtleBackground,
      brand: tokens.system.actions.primary.selected,
    },
    surface: {
      ...semantic.surface,
      default: tokens.core.surface,
      raised: tokens.backgroundAndSurface.raisedSurface,
      overlay: tokens.backgroundAndSurface.overlaySurface,
      sunken: tokens.backgroundAndSurface.subtleBackground,
      subtle: tokens.backgroundAndSurface.subtleBackground,
    },
    text: {
      ...semantic.text,
      primary: tokens.text.primary,
      secondary: tokens.text.secondary,
      tertiary: tokens.text.tertiary,
      disabled: tokens.text.disabled,
      inverse: tokens.text.inverse,
      link: tokens.text.link,
      brand: tokens.text.link,
      danger: tokens.system.statuses.danger.text,
      success: tokens.system.statuses.success.text,
      warning: tokens.system.statuses.warning.text,
    },
    border: {
      ...semantic.border,
      subtle: tokens.border.subtle,
      default: tokens.border.default,
      strong: tokens.border.strong,
      focus: tokens.border.focus,
      disabled: tokens.interaction.disabledBorder,
      danger: tokens.status.danger,
    },
    primary: {
      ...semantic.primary,
      default: tokens.core.primary,
      hover: tokens.interaction.primaryHover,
      pressed: tokens.interaction.primaryPressed,
      selected: tokens.interaction.primarySelected,
      subtle: tokens.core.primarySubtle,
      border: tokens.border.focus,
      text: tokens.text.link,
      onPrimary: tokens.core.onPrimary,
    },
    secondary: {
      ...semantic.secondary,
      default: tokens.core.secondary,
      hover: tokens.interaction.secondaryHover,
      pressed: tokens.interaction.secondaryPressed,
      onSecondary: tokens.core.onSecondary,
      selected: tokens.system.actions.secondary.selected,
      subtle: tokens.system.actions.secondary.selected,
      text: tokens.system.actions.secondary.selectedText,
      border: tokens.system.actions.secondary.selectedBorder,
    },
    accent: {
      ...semantic.accent,
      default: tokens.core.accent,
      onAccent: tokens.core.onAccent,
      hover: tokens.system.actions.accent.hover,
      pressed: tokens.system.actions.accent.pressed,
      selected: tokens.system.actions.accent.selected,
      subtle: tokens.system.actions.accent.selected,
      text: tokens.system.actions.accent.selectedText,
      border: tokens.system.actions.accent.selectedBorder,
    },
    success: {
      ...semantic.success,
      default: tokens.status.success,
      surface: tokens.status.successSurface,
      text: tokens.system.statuses.success.text,
      border: tokens.system.statuses.success.border,
      hover: tokens.system.statuses.success.hover,
      onSuccess: tokens.status.onSuccess,
    },
    warning: {
      ...semantic.warning,
      default: tokens.status.warning,
      surface: tokens.status.warningSurface,
      text: tokens.system.statuses.warning.text,
      border: tokens.system.statuses.warning.border,
      hover: tokens.system.statuses.warning.hover,
      onWarning: tokens.status.onWarning,
    },
    danger: {
      ...semantic.danger,
      default: tokens.status.danger,
      surface: tokens.status.dangerSurface,
      text: tokens.system.statuses.danger.text,
      border: tokens.system.statuses.danger.border,
      hover: tokens.system.statuses.danger.hover,
      pressed: tokens.system.statuses.danger.pressed,
      onDanger: tokens.status.onDanger,
    },
    info: {
      ...semantic.info,
      default: tokens.status.info,
      surface: tokens.status.infoSurface,
      text: tokens.system.statuses.info.text,
      border: tokens.system.statuses.info.border,
      onInfo: tokens.status.onInfo,
    },
    interaction: {
      ...semantic.interaction,
      hover: tokens.interaction.neutralHover,
      pressed: tokens.interaction.neutralPressed,
      selected: tokens.interaction.primarySelected,
      focusRing: tokens.interaction.focusRing,
      disabledBackground: tokens.interaction.disabledSurface,
      disabledForeground: tokens.text.disabled,
      selection: tokens.interaction.primarySelected,
      primaryHover: tokens.interaction.primaryHover,
      primaryPressed: tokens.interaction.primaryPressed,
      primarySelected: tokens.interaction.primarySelected,
      secondaryHover: tokens.interaction.secondaryHover,
      secondaryPressed: tokens.interaction.secondaryPressed,
      neutralHover: tokens.interaction.neutralHover,
      neutralPressed: tokens.interaction.neutralPressed,
      disabledSurface: tokens.interaction.disabledSurface,
      disabledBorder: tokens.interaction.disabledBorder,
    },
  };
}
