import type { SemanticTokens } from "@/lib/color-engine/types";
import type { PaletteTokens } from "./types";

export function applyGeneratedToSemantic(
  semantic: SemanticTokens,
  tokens: PaletteTokens,
): SemanticTokens {
  return {
    ...semantic,
    background: {
      ...semantic.background,
      canvas: tokens.backgroundAndSurface.background,
      subtle: tokens.backgroundAndSurface.subtleBackground,
    },
    surface: {
      ...semantic.surface,
      default: tokens.core.surface,
      raised: tokens.backgroundAndSurface.raisedSurface,
      overlay: tokens.backgroundAndSurface.overlaySurface,
      sunken: tokens.backgroundAndSurface.subtleBackground,
    },
    text: {
      ...semantic.text,
      primary: tokens.text.primary,
      secondary: tokens.text.secondary,
      tertiary: tokens.text.tertiary,
      disabled: tokens.text.disabled,
      inverse: tokens.text.inverse,
      link: tokens.text.link,
      danger: tokens.status.danger,
      success: tokens.status.success,
      warning: tokens.status.warning,
    },
    border: {
      ...semantic.border,
      subtle: tokens.border.subtle,
      default: tokens.border.default,
      strong: tokens.border.strong,
      focus: tokens.border.focus,
      disabled: tokens.interaction.disabledBorder,
      danger: tokens.status.danger,
    },
    primary: {
      ...semantic.primary,
      default: tokens.core.primary,
      hover: tokens.interaction.primaryHover,
      pressed: tokens.interaction.primaryPressed,
      selected: tokens.interaction.primarySelected,
      subtle: tokens.core.primarySubtle,
      border: tokens.border.focus,
      text: tokens.text.link,
      onPrimary: tokens.core.onPrimary,
    },
    secondary: {
      ...semantic.secondary,
      default: tokens.core.secondary,
      hover: tokens.interaction.secondaryHover,
      pressed: tokens.interaction.secondaryPressed,
      onSecondary: tokens.core.onSecondary,
    },
    accent: {
      ...semantic.accent,
      default: tokens.core.accent,
      onAccent: tokens.core.onAccent,
    },
    success: {
      ...semantic.success,
      default: tokens.status.success,
      surface: tokens.status.successSurface,
      text: tokens.status.success,
      onSuccess: tokens.status.onSuccess,
    },
    warning: {
      ...semantic.warning,
      default: tokens.status.warning,
      surface: tokens.status.warningSurface,
      text: tokens.status.warning,
      onWarning: tokens.status.onWarning,
    },
    danger: {
      ...semantic.danger,
      default: tokens.status.danger,
      surface: tokens.status.dangerSurface,
      text: tokens.status.danger,
      onDanger: tokens.status.onDanger,
    },
    info: {
      ...semantic.info,
      default: tokens.status.info,
      surface: tokens.status.infoSurface,
      text: tokens.status.info,
      onInfo: tokens.status.onInfo,
    },
    interaction: {
      ...semantic.interaction,
      hover: tokens.interaction.neutralHover,
      pressed: tokens.interaction.neutralPressed,
      selected: tokens.interaction.primarySelected,
      focusRing: tokens.interaction.focusRing,
      disabledBackground: tokens.interaction.disabledSurface,
      disabledForeground: tokens.text.disabled,
      selection: tokens.interaction.primarySelected,
      primaryHover: tokens.interaction.primaryHover,
      primaryPressed: tokens.interaction.primaryPressed,
      primarySelected: tokens.interaction.primarySelected,
      secondaryHover: tokens.interaction.secondaryHover,
      secondaryPressed: tokens.interaction.secondaryPressed,
      neutralHover: tokens.interaction.neutralHover,
      neutralPressed: tokens.interaction.neutralPressed,
      disabledSurface: tokens.interaction.disabledSurface,
      disabledBorder: tokens.interaction.disabledBorder,
    },
  };
}
