import type { PaletteConcept, PaletteConceptId } from "./types";

export const DEFAULT_PALETTE_ID: PaletteConceptId = "balance";

export const PALETTE_CONCEPTS: PaletteConcept[] = [
  {
    id: "balance",
    group: "harmony",
    name: "Balance",
    impression: { ko: "가장 범용적이고 안정적", en: "The most versatile, stable default" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 40, chromaRatio: 0.7 },
      accentRule: { kind: "rotate", degrees: -75, chromaRatio: 0.85 },
      neutralHue: { kind: "primary" },
      neutralChroma: 0.01,
      surfaceProfile: "soft",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "monochrome",
    group: "harmony",
    name: "Monochrome",
    impression: { ko: "하나의 색으로 통일", en: "Unified by a single hue" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "same", chromaRatio: 0.55, lightnessDelta: 0.16 },
      accentRule: { kind: "same", chromaRatio: 0.9, lightnessDelta: -0.16 },
      neutralHue: { kind: "primary" },
      neutralChroma: 0.014,
      surfaceProfile: "tinted",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "tonal",
    group: "harmony",
    name: "Tonal",
    impression: { ko: "밝고 어두운 톤 중심", en: "Built from light and dark tones" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "same", chromaRatio: 0.4, lightness: 0.8 },
      accentRule: { kind: "same", chromaRatio: 0.8, lightness: 0.4 },
      neutralHue: { kind: "primary" },
      neutralChroma: 0.018,
      surfaceProfile: "tinted",
      contrastProfile: "strong",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "neighbor",
    group: "harmony",
    name: "Neighbor",
    impression: { ko: "자연스럽고 편안한 조화", en: "A natural, easy neighboring harmony" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 25, chromaRatio: 0.7 },
      accentRule: { kind: "rotate", degrees: -25, chromaRatio: 0.85 },
      neutralHue: { kind: "mid-ps" },
      neutralChroma: 0.012,
      surfaceProfile: "soft",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "analogous-flow",
    group: "harmony",
    name: "Analogous Flow",
    impression: { ko: "컬러가 한 방향으로 흐르는 느낌", en: "Color flowing in one direction" },
    tags: ["calm", "vivid"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 40, chromaRatio: 0.7 },
      accentRule: { kind: "rotate", degrees: 80, chromaRatio: 0.85 },
      neutralHue: { kind: "mean-psa" },
      neutralChroma: 0.014,
      surfaceProfile: "soft",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "complement",
    group: "harmony",
    name: "Complement",
    impression: { ko: "하나의 포인트가 명확한 조합", en: "One clear complementary point" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "same", chromaRatio: 0.45 },
      accentRule: { kind: "rotate", degrees: 180, chromaRatio: 0.85 },
      neutralHue: { kind: "primary" },
      neutralChroma: 0.004,
      surfaceProfile: "crisp",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "split-complement",
    group: "harmony",
    name: "Split Complement",
    impression: { ko: "보색보다 부드러운 대비", en: "Softer than a full complement" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 150, chromaRatio: 0.7 },
      accentRule: { kind: "rotate", degrees: -150, chromaRatio: 0.75 },
      neutralHue: { kind: "primary" },
      neutralChroma: 0.004,
      surfaceProfile: "crisp",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "triad",
    group: "harmony",
    name: "Triad",
    impression: { ko: "균형 잡힌 3색 조합", en: "A balanced three-hue set" },
    tags: ["vivid"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 120, chromaRatio: 0.7 },
      accentRule: { kind: "rotate", degrees: -120, chromaRatio: 0.8 },
      neutralHue: { kind: "achromatic" },
      neutralChroma: 0.003,
      surfaceProfile: "crisp",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.95,
    },
  },
  {
    id: "square",
    group: "expressive",
    name: "Square",
    impression: { ko: "다채롭고 구조적인 대비", en: "Colorful, structured contrast" },
    tags: ["vivid", "contrast"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 90, chromaRatio: 0.75 },
      accentRule: { kind: "rotate", degrees: 180, chromaRatio: 0.8 },
      neutralHue: { kind: "achromatic" },
      neutralChroma: 0.002,
      surfaceProfile: "crisp",
      contrastProfile: "strong",
      colorStrength: "high",
      semanticIntensity: 1,
    },
  },
  {
    id: "highlight",
    group: "expressive",
    name: "Highlight",
    impression: { ko: "Primary 중심, Accent만 강하게", en: "Primary-led, with a sharp accent" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "mix-neutral", primaryRatio: 0.3 },
      accentRule: { kind: "rotate", degrees: 180, chromaRatio: 0.95 },
      neutralHue: { kind: "primary" },
      neutralChroma: 0.004,
      surfaceProfile: "crisp",
      contrastProfile: "strong",
      colorStrength: "medium",
      semanticIntensity: 1,
    },
  },
  {
    id: "vivid-pop",
    group: "expressive",
    name: "Vivid Pop",
    impression: { ko: "선명하고 디지털한 분위기", en: "Sharp, digital, high-chroma" },
    tags: ["vivid", "contrast"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 65, chromaRatio: 0.95 },
      accentRule: { kind: "rotate", degrees: -95, chromaRatio: 1.05 },
      neutralHue: { kind: "achromatic" },
      neutralChroma: 0.003,
      surfaceProfile: "crisp",
      contrastProfile: "strong",
      colorStrength: "high",
      semanticIntensity: 1,
    },
  },
  {
    id: "playful",
    group: "expressive",
    name: "Playful",
    impression: { ko: "친근하고 재미있는 분위기", en: "Friendly and playful" },
    tags: ["vivid"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 100, chromaRatio: 0.8, lightness: 0.72 },
      accentRule: { kind: "rotate", degrees: -55, chromaRatio: 0.95, lightness: 0.6 },
      neutralHue: { kind: "fixed", hue: 65 },
      neutralChroma: 0.012,
      surfaceProfile: "soft",
      contrastProfile: "normal",
      colorStrength: "high",
      semanticIntensity: 1,
    },
  },
  {
    id: "soft-pastel",
    group: "soft-natural",
    name: "Soft Pastel",
    impression: { ko: "밝고 부드러운 파스텔", en: "Bright, soft pastels" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 35, chromaRatio: 1, lightness: 0.84, chromaCap: 0.1 },
      accentRule: { kind: "rotate", degrees: -45, chromaRatio: 1, lightness: 0.78, chromaCap: 0.12 },
      neutralHue: { kind: "primary" },
      neutralChroma: 0.02,
      surfaceProfile: "soft",
      contrastProfile: "soft",
      colorStrength: "medium",
      semanticIntensity: 0.8,
    },
  },
  {
    id: "dusty",
    group: "soft-natural",
    name: "Dusty",
    impression: { ko: "빈티지하고 흐릿한 색감", en: "Vintage, dusty color" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "rotate", degrees: 25, chromaRatio: 0.28 },
      accentRule: { kind: "rotate", degrees: -35, chromaRatio: 0.38 },
      neutralHue: { kind: "fixed", hue: 70 },
      neutralChroma: 0.018,
      surfaceProfile: "paper",
      contrastProfile: "soft",
      colorStrength: "low",
      semanticIntensity: 0.8,
    },
  },
  {
    id: "natural",
    group: "soft-natural",
    name: "Natural",
    impression: { ko: "자연·웰니스·생활 브랜드", en: "Nature, wellness, everyday brands" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "towards", hue: 145, amount: 0.55 },
      accentRule: { kind: "towards", hue: 80, amount: 0.45 },
      neutralHue: { kind: "fixed", hue: 120 },
      neutralChroma: 0.016,
      surfaceProfile: "paper",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.85,
    },
  },
  {
    id: "fresh-air",
    group: "soft-natural",
    name: "Fresh Air",
    impression: { ko: "청량하고 가벼운 느낌", en: "Light and airy" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "towards", hue: 165, amount: 0.55 },
      accentRule: { kind: "towards", hue: 235, amount: 0.5 },
      neutralHue: { kind: "fixed", hue: 210 },
      neutralChroma: 0.012,
      surfaceProfile: "soft",
      contrastProfile: "normal",
      colorStrength: "medium",
      semanticIntensity: 0.85,
    },
  },
  {
    id: "clean",
    group: "professional",
    name: "Clean",
    impression: { ko: "SaaS·생산성 도구에 적합", en: "Built for SaaS and productivity" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "same", chromaRatio: 0.35, lightnessDelta: 0.18 },
      accentRule: { kind: "rotate", degrees: 60, chromaRatio: 0.65 },
      neutralHue: { kind: "achromatic" },
      neutralChroma: 0.002,
      surfaceProfile: "crisp",
      contrastProfile: "normal",
      colorStrength: "low",
      semanticIntensity: 0.9,
    },
  },
  {
    id: "minimal-gray",
    group: "professional",
    name: "Minimal Gray",
    impression: { ko: "Primary 하나만 강조", en: "Only Primary carries the color" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "mix-neutral", primaryRatio: 0.2 },
      accentRule: { kind: "dark-tone", chromaRatio: 0.85, lightnessDelta: -0.22 },
      neutralHue: { kind: "achromatic" },
      neutralChroma: 0.001,
      surfaceProfile: "crisp",
      contrastProfile: "strong",
      colorStrength: "low",
      semanticIntensity: 0.9,
    },
  },
  {
    id: "warm-neutral",
    group: "professional",
    name: "Warm Neutral",
    impression: { ko: "따뜻하고 인간적인 제품", en: "Warm, human product color" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "towards", hue: 70, amount: 0.35 },
      accentRule: { kind: "towards", hue: 35, amount: 0.35 },
      neutralHue: { kind: "fixed", hue: 70 },
      neutralChroma: 0.014,
      surfaceProfile: "soft",
      contrastProfile: "normal",
      colorStrength: "low",
      semanticIntensity: 0.9,
    },
  },
  {
    id: "cool-neutral",
    group: "professional",
    name: "Cool Neutral",
    impression: { ko: "기술적이고 정돈된 제품", en: "Technical and orderly" },
    tags: ["calm"],
    preset: {
      secondaryRule: { kind: "towards", hue: 235, amount: 0.35 },
      accentRule: { kind: "towards", hue: 195, amount: 0.35 },
      neutralHue: { kind: "fixed", hue: 235 },
      neutralChroma: 0.012,
      surfaceProfile: "crisp",
      contrastProfile: "normal",
      colorStrength: "low",
      semanticIntensity: 0.9,
    },
  },
  {
    id: "classy",
    group: "professional",
    name: "Classy",
    impression: { ko: "고급스럽고 절제된 느낌", en: "Refined and restrained" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "darken-low-chroma", chromaRatio: 0.35, lightnessDelta: -0.18 },
      accentRule: { kind: "rotate", degrees: 30, chromaRatio: 0.55 },
      neutralHue: { kind: "fixed", hue: 70 },
      neutralChroma: 0.01,
      surfaceProfile: "paper",
      contrastProfile: "strong",
      colorStrength: "low",
      semanticIntensity: 0.8,
    },
  },
  {
    id: "editorial",
    group: "professional",
    name: "Editorial",
    impression: { ko: "매거진·콘텐츠 중심", en: "Magazine and content-led" },
    tags: ["contrast"],
    preset: {
      secondaryRule: { kind: "mix-charcoal" },
      accentRule: { kind: "rotate", degrees: 180, chromaRatio: 0.55 },
      neutralHue: { kind: "fixed", hue: 75 },
      neutralChroma: 0.008,
      surfaceProfile: "paper",
      contrastProfile: "strong",
      colorStrength: "low",
      semanticIntensity: 0.85,
    },
  },
];

export const PALETTE_CONCEPT_MAP = Object.fromEntries(
  PALETTE_CONCEPTS.map((concept) => [concept.id, concept]),
) as Record<PaletteConceptId, PaletteConcept>;

const LEGACY_PALETTE_IDS: Record<string, PaletteConceptId> = {
  "generic-gradient": "balance",
  "matching-gradient": "neighbor",
  spot: "warm-neutral",
  "twisted-spot": "playful",
  classy: "classy",
  cube: "tonal",
  switch: "cool-neutral",
  "small-switch": "cool-neutral",
  "skip-gradient": "complement",
  natural: "natural",
  matching: "natural",
  squash: "complement",
  "grey-friends": "minimal-gray",
  dotting: "playful",
  "skip-shade": "fresh-air",
  threedom: "triad",
  highlight: "highlight",
  neighbor: "neighbor",
  discreet: "dusty",
  "muted-calm": "dusty",
  earthy: "natural",
  dust: "dusty",
  collective: "split-complement",
  friend: "natural",
  pin: "editorial",
  shades: "tonal",
  "random-shades": "vivid-pop",
};

export function isPaletteConceptId(id: string): id is PaletteConceptId {
  return id in PALETTE_CONCEPT_MAP;
}

export function resolvePaletteId(id?: string | null): PaletteConceptId {
  if (id && isPaletteConceptId(id)) return id;
  if (id && LEGACY_PALETTE_IDS[id]) return LEGACY_PALETTE_IDS[id];
  return DEFAULT_PALETTE_ID;
}

export function getPaletteConcept(id?: string | null) {
  return PALETTE_CONCEPT_MAP[resolvePaletteId(id)];
}

export function conceptsInGroup(group?: PaletteConcept["group"] | "all") {
  if (!group || group === "all") return PALETTE_CONCEPTS;
  return PALETTE_CONCEPTS.filter((concept) => concept.group === group);
}
